const startDate1: Date = new Date();
const endDate1: Date = new Date(startDate1);
endDate1.setDate(startDate1.getDate() + 2);

const startDate2: Date = new Date(endDate1);
startDate2.setDate(endDate1.getDate() + 1);
const endDate2: Date = new Date(startDate2);
endDate2.setDate(startDate2.getDate() + 2);

const startDate3: Date = new Date(endDate2);
startDate3.setDate(endDate2.getDate() + 5);
const endDate3: Date = new Date(startDate3);
endDate3.setDate(startDate3.getDate() + 5);

const startDate4: Date = new Date(endDate3);
startDate4.setDate(endDate3.getDate() + 5);
const endDate4: Date = new Date(startDate4);
endDate4.setDate(startDate4.getDate() + 5);

const startDate5: Date = new Date(endDate4);
startDate5.setDate(endDate4.getDate() + 2);
const endDate5: Date = new Date(startDate5);
endDate5.setDate(startDate5.getDate() + 2);

const hotelData: Hotel[] = [
    {
        HotelID: 102278,
        HotelName: 'Benor Hotel',
        Address: "59 rue de l'Abbaye",
        Description: 'We are a top hotel, providing comfort and luxury. Our warm hospitality makes every stay special. Enjoy a memorable experience with us.',
        HotelImgID: 'hotel_1',
        Rating: 5,
        ReviewCount: 20,
        Location: { latitude: 45.322690, longitude: -106.781689, TooltipContent: 'Benor Hotel, Montana' },
        HotelFacility: 'Parking, Pet allowed, Swiming pool, Restaurant',
        RoomID: 1,
        RoomImgID: 'room_1',
        RoomName: 'Alpha Room',
        Capacity: 6,
        ExtraBed: 3,
        ExtraBedCost: 200,
        DiscountPercentage: 8,
        TaxPercentage: 5,
        Extras: 'Free cancellation, Credit card accepted, Pay at visit',
        RoomFacility: 'Television, Projector, Balcony, Whiteboard, Kitchen, Internet, Shower',
        Price: 500,
        CheckInOut: [{ CheckIn: startDate3, CheckOut: endDate3 }]
    },
    {
        HotelID: 102278,
        HotelName: 'Benor Hotel',
        Address: "59 rue de l'Abbaye",
        Description: 'We are a top hotel, providing comfort and luxury. Our warm hospitality makes every stay special. Enjoy a memorable experience with us.',
        HotelImgID: 'hotel_1',
        Rating: 5,
        ReviewCount: 20,
        Location: { latitude: 45.322690, longitude: -106.781689, TooltipContent: 'Benor Hotel, Montana' },
        HotelFacility: 'Parking, Pet allowed, Swiming pool, Restaurant',
        RoomID: 2,
        RoomImgID: 'room_2',
        RoomName: 'Beta Room',
        Capacity: 4,
        ExtraBed: 2,
        ExtraBedCost: 300,
        DiscountPercentage: 9,
        TaxPercentage: 6,
        Extras: 'Credit card accepted, Pay at visit',
        RoomFacility: 'Television, Whiteboard, Kitchen, Internet',
        Price: 300,
        CheckInOut: [{ CheckIn: startDate1, CheckOut: endDate1 }, { CheckIn: startDate3, CheckOut: endDate3 }]
    },
    {
        HotelID: 102278,
        HotelName: 'Benor Hotel',
        Address: "59 rue de l'Abbaye",
        Description: 'We are a top hotel, providing comfort and luxury. Our warm hospitality makes every stay special. Enjoy a memorable experience with us.',
        HotelImgID: 'hotel_1',
        Rating: 5,
        ReviewCount: 20,
        Location: { latitude: 45.322690, longitude: -106.781689, TooltipContent: 'Benor Hotel, Montana' },
        HotelFacility: 'Parking, Pet allowed, Swiming pool, Restaurant',
        RoomID: 3,
        RoomImgID: 'room_3',
        RoomName: 'Gamma Room',
        Capacity: 2,
        ExtraBed: 2,
        ExtraBedCost: 150,
        DiscountPercentage: 6,
        TaxPercentage: 3,
        Extras: 'Free cancellation, Pay at visit',
        RoomFacility: 'Television, Internet',
        Price: 150,
        CheckInOut: [{ CheckIn: startDate4, CheckOut: endDate4 }]
    },
    {
        HotelID: 117823,
        HotelName: 'Zabator Hotel',
        Address: "Luisenstr. 48",
        Description: 'A pleasant hotel for pleasant people. We offer comfort, warmth, and great service. Stay with us for a relaxing experience.',
        HotelImgID: 'hotel_2',
        Rating: 4,
        ReviewCount: 30,
        Location: { latitude: 40.633829, longitude: -73.967230, TooltipContent: 'Zabator Hotel, New York' },
        HotelFacility: 'Parking, Swiming pool, Restaurant',
        RoomID: 1,
        RoomImgID: 'room_4',
        RoomName: 'Alpha Room',
        Capacity: 7,
        ExtraBed: 5,
        ExtraBedCost: 100,
        DiscountPercentage: 10,
        TaxPercentage: 7,
        Extras: 'Free cancellation',
        RoomFacility: 'Television, Projector, Balcony, Kitchen, Internet',
        Price: 600,
        CheckInOut: [{ CheckIn: startDate1, CheckOut: endDate1 }, { CheckIn: startDate2, CheckOut: endDate2 }]
    },
    {
        HotelID: 117823,
        HotelName: 'Zabator Hotel',
        Address: "Luisenstr. 48",
        Description: 'A pleasant hotel for pleasant people. We offer comfort, warmth, and great service. Stay with us for a relaxing experience.',
        HotelImgID: 'hotel_2',
        Rating: 4,
        ReviewCount: 30,
        Location: { latitude: 40.633829, longitude: -73.967230, TooltipContent: 'Zabator Hotel, New York' },
        HotelFacility: 'Parking, Swiming pool, Restaurant',
        RoomID: 2,
        RoomImgID: 'room_5',
        RoomName: 'Beta Room',
        Capacity: 3,
        ExtraBed: 3,
        ExtraBedCost: 200,
        DiscountPercentage: 7,
        TaxPercentage: 4,
        Extras: 'Pay at visit',
        RoomFacility: 'Television, Kitchen, Internet',
        Price: 300,
        CheckInOut: [{ CheckIn: startDate2, CheckOut: endDate2 }, { CheckIn: startDate3, CheckOut: endDate3 }]
    },
    {
        HotelID: 117823,
        HotelName: 'Zabator Hotel',
        Address: "Luisenstr. 48",
        Description: 'A pleasant hotel for pleasant people. We offer comfort, warmth, and great service. Stay with us for a relaxing experience.',
        HotelImgID: 'hotel_2',
        Rating: 4,
        ReviewCount: 30,
        Location: { latitude: 40.633829, longitude: -73.967230, TooltipContent: 'Zabator Hotel, New York' },
        HotelFacility: 'Parking, Swiming pool, Restaurant',
        RoomID: 3,
        RoomImgID: 'room_6',
        RoomName: 'Gamma Room',
        Capacity: 2,
        ExtraBed: 3,
        ExtraBedCost: 300,
        DiscountPercentage: 5,
        TaxPercentage: 2,
        Extras: 'Free cancellation',
        RoomFacility: 'Television, Internet',
        Price: 100,
        CheckInOut: [{ CheckIn: startDate5, CheckOut: endDate5 }]
    },
    {
        HotelID: 322211,
        HotelName: 'Ben Swikator',
        Address: "Rua do Paço, 67",
        Description: 'Want to explore the peaceful waves and a marvelous hotel? Experience serenity and luxury with us. Enjoy a stay like no other.',
        HotelImgID: 'hotel_3',
        Rating: 3,
        ReviewCount: 18,
        Location: { latitude: 37.341648, longitude: -121.197788, TooltipContent: 'Ben Swikator, California' },
        HotelFacility: 'Parking, Restaurant, Spa',
        RoomID: 1,
        RoomImgID: 'room_7',
        RoomName: 'Alpha Room',
        Capacity: 5,
        ExtraBed: 1,
        ExtraBedCost: 500,
        DiscountPercentage: 12,
        TaxPercentage: 9,
        Extras: 'Free cancellation, Credit card accepted, Pay at visit',
        RoomFacility: 'Television, Kitchen, Internet, Shower',
        Price: 600,
        CheckInOut: [{ CheckIn: startDate5, CheckOut: endDate5 }]
    },
    {
        HotelID: 322211,
        HotelName: 'Ben Swikator',
        Address: "Rua do Paço, 67",
        Description: 'Want to explore the peaceful waves and a marvelous hotel? Experience serenity and luxury with us. Enjoy a stay like no other.',
        HotelImgID: 'hotel_3',
        Rating: 3,
        ReviewCount: 18,
        Location: { latitude: 37.341648, longitude: -121.197788, TooltipContent: 'Ben Swikator, California' },
        HotelFacility: 'Parking, Restaurant, Spa',
        RoomID: 2,
        RoomImgID: 'room_8',
        RoomName: 'Beta Room',
        Capacity: 4,
        ExtraBed: 3,
        ExtraBedCost: 100,
        DiscountPercentage: 8,
        TaxPercentage: 5,
        Extras: 'Free cancellation',
        RoomFacility: 'Television, Internet, Shower',
        Price: 300,
        CheckInOut: [{ CheckIn: startDate1, CheckOut: endDate1 }]
    },
    {
        HotelID: 322211,
        HotelName: 'Ben Swikator',
        Address: "Rua do Paço, 67",
        Description: 'Want to explore the peaceful waves and a marvelous hotel? Experience serenity and luxury with us. Enjoy a stay like no other.',
        HotelImgID: 'hotel_3',
        Rating: 3,
        ReviewCount: 18,
        Location: { latitude: 37.341648, longitude: -121.197788, TooltipContent: 'Ben Swikator, California' },
        HotelFacility: 'Parking, Restaurant, Spa',
        RoomID: 3,
        RoomImgID: 'room_9',
        RoomName: 'Gamma Room',
        Capacity: 3,
        ExtraBed: 3,
        ExtraBedCost: 250,
        DiscountPercentage: 8,
        TaxPercentage: 5,
        Extras: 'Free cancellation',
        RoomFacility: 'Internet, Shower',
        Price: 150,
        CheckInOut: [{ CheckIn: startDate2, CheckOut: endDate2 }, { CheckIn: startDate3, CheckOut: endDate3 }]
    },
    {
        HotelID: 112278,
        HotelName: 'Zentor Hotel',
        Address: "2, rue du Commerce",
        Description: 'We are the queen of hospitality, offering elegance and comfort. Our hotel provides a royal experience for every guest. Stay with us and feel the luxury.',
        HotelImgID: 'hotel_4',
        Rating: 4,
        ReviewCount: 35,
        Location: { latitude: 45.322690, longitude: -106.781689, TooltipContent: 'Zentor Hotel, Montana' },
        HotelFacility: 'Parking, Pet allowed, Swiming pool',
        RoomID: 1,
        RoomImgID: 'room_10',
        RoomName: 'Alpha Room',
        Capacity: 6,
        ExtraBed: 5,
        ExtraBedCost: 300,
        DiscountPercentage: 10,
        TaxPercentage: 7,
        Extras: 'Free cancellation',
        RoomFacility: 'Television, Projector, Balcony, Whiteboard, Kitchen, Internet, Shower',
        Price: 500,
        CheckInOut: [{ CheckIn: startDate4, CheckOut: endDate4 }]
    },
    {
        HotelID: 112278,
        HotelName: 'Zentor Hotel',
        Address: "2, rue du Commerce",
        Description: 'We are the queen of hospitality, offering elegance and comfort. Our hotel provides a royal experience for every guest. Stay with us and feel the luxury.',
        HotelImgID: 'hotel_4',
        Rating: 4,
        ReviewCount: 35,
        Location: { latitude: 45.322690, longitude: -106.781689, TooltipContent: 'Zentor Hotel, Montana' },
        HotelFacility: 'Parking, Pet allowed, Swiming pool',
        RoomID: 2,
        RoomImgID: 'room_11',
        RoomName: 'Beta Room',
        Capacity: 4,
        ExtraBed: 3,
        ExtraBedCost: 200,
        DiscountPercentage: 5,
        TaxPercentage: 2,
        Extras: 'Free cancellation, Credit card accepted, Pay at visit',
        RoomFacility: 'Television, Whiteboard, Kitchen, Internet',
        Price: 300,
        CheckInOut: [{ CheckIn: startDate1, CheckOut: endDate1 }]
    },
    {
        HotelID: 112278,
        HotelName: 'Zentor Hotel',
        Address: "2, rue du Commerce",
        Description: 'We are the queen of hospitality, offering elegance and comfort. Our hotel provides a royal experience for every guest. Stay with us and feel the luxury.',
        HotelImgID: 'hotel_4',
        Rating: 4,
        ReviewCount: 35,
        Location: { latitude: 45.322690, longitude: -106.781689, TooltipContent: 'Zentor Hotel, Montana' },
        HotelFacility: 'Parking, Pet allowed, Swiming pool',
        RoomID: 3,
        RoomImgID: 'room_12',
        RoomName: 'Gamma Room',
        Capacity: 2,
        ExtraBed: 3,
        ExtraBedCost: 200,
        DiscountPercentage: 8,
        TaxPercentage: 3,
        Extras: 'Free cancellation, Pay at visit',
        RoomFacility: 'Television, Internet',
        Price: 150,
        CheckInOut: [{ CheckIn: startDate4, CheckOut: endDate4 }]
    },
    {
        HotelID: 127823,
        HotelName: 'Bakator Hotel',
        Address: "Boulevard Tirou, 255",
        Description: 'A pleasant hotel for sweet people. We offer warmth, comfort, and great service. Enjoy a delightful stay with us.',
        HotelImgID: 'hotel_5',
        Rating: 2,
        ReviewCount: 15,
        Location: { latitude: 40.633829, longitude: -73.967230, TooltipContent: 'Bakator Hotel, New York' },
        HotelFacility: 'Swiming pool, Restaurant',
        RoomID: 1,
        RoomImgID: 'room_13',
        RoomName: 'Alpha Room',
        Capacity: 7,
        ExtraBed: 3,
        ExtraBedCost: 200,
        DiscountPercentage: 8,
        TaxPercentage: 2,
        Extras: 'Free cancellation, Credit card accepted, Pay at visit',
        RoomFacility: 'Television, Projector, Balcony, Kitchen, Internet',
        Price: 600,
        CheckInOut: [{ CheckIn: startDate1, CheckOut: endDate1 }, { CheckIn: startDate2, CheckOut: endDate2 }, { CheckIn: startDate3, CheckOut: endDate3 }]
    },
    {
        HotelID: 127823,
        HotelName: 'Bakator Hotel',
        Address: "Boulevard Tirou, 255",
        Description: 'A pleasant hotel for sweet people. We offer warmth, comfort, and great service. Enjoy a delightful stay with us.',
        HotelImgID: 'hotel_5',
        Rating: 2,
        ReviewCount: 15,
        Location: { latitude: 40.633829, longitude: -73.967230, TooltipContent: 'Bakator Hotel, New York' },
        HotelFacility: 'Swiming pool, Restaurant',
        RoomID: 2,
        RoomImgID: 'room_14',
        RoomName: 'Beta Room',
        Capacity: 3,
        ExtraBed: 3,
        ExtraBedCost: 50,
        DiscountPercentage: 9,
        TaxPercentage: 5,
        Extras: 'Free cancellation, Pay at visit',
        RoomFacility: 'Television, Kitchen, Internet',
        Price: 300,
        CheckInOut: [{ CheckIn: startDate2, CheckOut: endDate2 }]
    },
    {
        HotelID: 127823,
        HotelName: 'Bakator Hotel',
        Address: "Boulevard Tirou, 255",
        Description: 'A pleasant hotel for sweet people. We offer warmth, comfort, and great service. Enjoy a delightful stay with us.',
        HotelImgID: 'hotel_5',
        Rating: 2,
        ReviewCount: 15,
        Location: { latitude: 40.633829, longitude: -73.967230, TooltipContent: 'Bakator Hotel, New York' },
        HotelFacility: 'Swiming pool, Restaurant',
        RoomID: 3,
        RoomImgID: 'room_15',
        RoomName: 'Gamma Room',
        Capacity: 2,
        ExtraBed: 2,
        ExtraBedCost: 200,
        DiscountPercentage: 9,
        TaxPercentage: 5,
        Extras: 'Free cancellation',
        RoomFacility: 'Television, Internet',
        Price: 100,
        CheckInOut: [{ CheckIn: startDate5, CheckOut: endDate5 }]
    },
    {
        HotelID: 332211,
        HotelName: 'Zen Swikator',
        Address: "Rua do Paço, GG",
        Description: 'Want to explore a stunning, silent sea in a marvelous hotel? Experience tranquility and luxury with us. Enjoy a peaceful and unforgettable stay.',
        HotelImgID: 'hotel_6',
        Rating: 5,
        ReviewCount: 22,
        Location: { latitude: 37.341648, longitude: -121.197788, TooltipContent: 'Zen Swikator, California' },
        HotelFacility: 'Restaurant',
        RoomID: 1,
        RoomImgID: 'room_16',
        RoomName: 'Alpha Room',
        Capacity: 5,
        ExtraBed: 1,
        ExtraBedCost: 100,
        DiscountPercentage: 7,
        TaxPercentage: 3,
        Extras: 'Free cancellation, Credit card accepted, Pay at visit',
        RoomFacility: 'Television, Kitchen, Internet, Shower',
        Price: 600,
        CheckInOut: [{ CheckIn: startDate3, CheckOut: endDate3 }]
    },
    {
        HotelID: 332211,
        HotelName: 'Zen Swikator',
        Address: "Rua do Paço, GG",
        Description: 'Want to explore a stunning, silent sea in a marvelous hotel? Experience tranquility and luxury with us. Enjoy a peaceful and unforgettable stay.',
        HotelImgID: 'hotel_6',
        Rating: 5,
        ReviewCount: 22,
        Location: { latitude: 37.341648, longitude: -121.197788, TooltipContent: 'Zen Swikator, California' },
        HotelFacility: 'Restaurant',
        RoomID: 2,
        RoomImgID: 'room_1',
        RoomName: 'Beta Room',
        Capacity: 4,
        ExtraBed: 3,
        ExtraBedCost: 500,
        DiscountPercentage: 9,
        TaxPercentage: 5,
        Extras: 'Free cancellation',
        RoomFacility: 'Television, Internet, Shower',
        Price: 300,
        CheckInOut: [{ CheckIn: startDate1, CheckOut: endDate1 }]
    },
    {
        HotelID: 332211,
        HotelName: 'Zen Swikator',
        Address: "Rua do Paço, GG",
        Description: 'Want to explore a stunning, silent sea in a marvelous hotel? Experience tranquility and luxury with us. Enjoy a peaceful and unforgettable stay.',
        HotelImgID: 'hotel_6',
        Rating: 5,
        ReviewCount: 22,
        Location: { latitude: 37.341648, longitude: -121.197788, TooltipContent: 'Zen Swikator, California' },
        HotelFacility: 'Restaurant',
        RoomID: 3,
        RoomImgID: 'room_2',
        RoomName: 'Gamma Room',
        Capacity: 3,
        ExtraBed: 3,
        ExtraBedCost: 200,
        DiscountPercentage: 8,
        TaxPercentage: 5,
        Extras: 'Pay at visit',
        RoomFacility: 'Internet, Shower',
        Price: 150,
        CheckInOut: [{ CheckIn: startDate2, CheckOut: endDate2 }]
    },
    {
        HotelID: 342211,
        HotelName: 'Cen Zwikator',
        Address: "Hauptstr. 31",
        Description: 'Want to explore a marvelous hotel? Experience luxury, comfort, and exceptional service. Stay with us for an unforgettable journey.',
        HotelImgID: 'hotel_7',
        Rating: 5,
        ReviewCount: 25,
        Location: { latitude: 37.341648, longitude: -121.197788, TooltipContent: 'Cen Zwikator, California' },
        HotelFacility: 'Spa',
        RoomID: 1,
        RoomImgID: 'room_3',
        RoomName: 'Alpha Room',
        Capacity: 5,
        ExtraBed: 3,
        ExtraBedCost: 50,
        DiscountPercentage: 8,
        TaxPercentage: 5,
        Extras: 'Free cancellation, Credit card accepted, Pay at visit',
        RoomFacility: 'Television, Kitchen, Internet, Shower',
        Price: 600,
        CheckInOut: [{ CheckIn: startDate3, CheckOut: endDate3 }]
    },
    {
        HotelID: 342211,
        HotelName: 'Cen Zwikator',
        Address: "Hauptstr. 31",
        Description: 'Want to explore a marvelous hotel? Experience luxury, comfort, and exceptional service. Stay with us for an unforgettable journey.',
        HotelImgID: 'hotel_7',
        Rating: 5,
        ReviewCount: 25,
        Location: { latitude: 37.341648, longitude: -121.197788, TooltipContent: 'Cen Zwikator, California' },
        HotelFacility: 'Spa',
        RoomID: 2,
        RoomImgID: 'room_4',
        RoomName: 'Beta Room',
        Capacity: 4,
        ExtraBed: 2,
        ExtraBedCost: 200,
        DiscountPercentage: 9,
        TaxPercentage: 5,
        Extras: 'Free cancellation, Credit card accepted, Pay at visit',
        RoomFacility: 'Television, Internet, Shower',
        Price: 300,
        CheckInOut: [{ CheckIn: startDate1, CheckOut: endDate1 }, { CheckIn: startDate3, CheckOut: endDate3 }]
    },
    {
        HotelID: 342211,
        HotelName: 'Cen Zwikator',
        Address: "Hauptstr. 31",
        Description: 'Want to explore a marvelous hotel? Experience luxury, comfort, and exceptional service. Stay with us for an unforgettable journey.',
        HotelImgID: 'hotel_7',
        Rating: 5,
        ReviewCount: 25,
        Location: { latitude: 37.341648, longitude: -121.197788, TooltipContent: 'Cen Zwikator, California' },
        HotelFacility: 'Spa',
        RoomID: 3,
        RoomImgID: 'room_5',
        RoomName: 'Gamma Room',
        Capacity: 3,
        ExtraBed: 2,
        ExtraBedCost: 200,
        DiscountPercentage: 8,
        TaxPercentage: 3,
        Extras: 'Free cancellation, Credit card accepted, Pay at visit',
        RoomFacility: 'Internet, Shower',
        Price: 150,
        CheckInOut: [{ CheckIn: startDate2, CheckOut: endDate2 }]
    },
    {
        HotelID: 132278,
        HotelName: 'Bekaor Hotel',
        Address: "68 rue de l'Abbaye",
        Description: 'We have a variety of themed hotels, each offering a unique experience. Enjoy a stay that matches your style and preferences. Discover comfort with a creative touch.',
        HotelImgID: 'hotel_8',
        Rating: 3,
        ReviewCount: 30,
        Location: { latitude: 45.322690, longitude: -106.781689, TooltipContent: 'Bekaor Hotel, Montana' },
        HotelFacility: 'Pet allowed, Swiming pool, Restaurant',
        RoomID: 1,
        RoomImgID: 'room_6',
        RoomName: 'Alpha Room',
        Capacity: 3,
        ExtraBed: 2,
        ExtraBedCost: 200,
        DiscountPercentage: 12,
        TaxPercentage: 5,
        Extras: 'Pay at visit',
        RoomFacility: 'Television, Kitchen, Internet, Shower',
        Price: 600,
        CheckInOut: [{ CheckIn: startDate3, CheckOut: endDate3 }]
    },
    {
        HotelID: 132278,
        HotelName: 'Bekaor Hotel',
        Address: "68 rue de l'Abbaye",
        Description: 'We have a variety of themed hotels, each offering a unique experience. Enjoy a stay that matches your style and preferences. Discover comfort with a creative touch.',
        HotelImgID: 'hotel_8',
        Rating: 3,
        ReviewCount: 30,
        Location: { latitude: 45.322690, longitude: -106.781689, TooltipContent: 'Bekaor Hotel, Montana' },
        HotelFacility: 'Pet allowed, Swiming pool, Restaurant',
        RoomID: 2,
        RoomImgID: 'room_7',
        RoomName: 'Beta Room',
        Capacity: 4,
        ExtraBed: 2,
        ExtraBedCost: 400,
        DiscountPercentage: 9,
        TaxPercentage: 3,
        Extras: 'Credit card accepted, Pay at visit',
        RoomFacility: 'Television, Whiteboard, Kitchen',
        Price: 200,
        CheckInOut: [{ CheckIn: startDate1, CheckOut: endDate1 }]
    },
    {
        HotelID: 132278,
        HotelName: 'Bekaor Hotel',
        Address: "68 rue de l'Abbaye",
        Description: 'We have a variety of themed hotels, each offering a unique experience. Enjoy a stay that matches your style and preferences. Discover comfort with a creative touch.',
        HotelImgID: 'hotel_8',
        Rating: 3,
        ReviewCount: 30,
        Location: { latitude: 45.322690, longitude: -106.781689, TooltipContent: 'Bekaor Hotel, Montana' },
        HotelFacility: 'Pet allowed, Swiming pool, Restaurant',
        RoomID: 3,
        RoomImgID: 'room_8',
        RoomName: 'Gamma Room',
        Capacity: 2,
        ExtraBed: 2,
        ExtraBedCost: 250,
        DiscountPercentage: 6,
        TaxPercentage: 3,
        Extras: 'Free cancellation, Pay at visit',
        RoomFacility: 'Television, Internet',
        Price: 150,
        CheckInOut: [{ CheckIn: startDate3, CheckOut: endDate3 }]
    },
    {
        HotelID: 137823,
        HotelName: 'Zanator Hotel',
        Address: "Luisenstr. 56",
        Description: 'A pleasant hotel for polite people. We offer comfort, warmth, and excellent service. Enjoy a relaxing and memorable stay with us.',
        HotelImgID: 'hotel_9',
        Rating: 5,
        ReviewCount: 50,
        Location: { latitude: 40.633829, longitude: -73.967230, TooltipContent: 'Zanator Hotel, New York' },
        HotelFacility: 'Parking, Pet allowed',
        RoomID: 1,
        RoomImgID: 'room_9',
        RoomName: 'Alpha Room',
        Capacity: 5,
        ExtraBed: 1,
        ExtraBedCost: 400,
        DiscountPercentage: 10,
        TaxPercentage: 6,
        Extras: 'Free cancellation',
        RoomFacility: 'Television, Projector, Balcony',
        Price: 600,
        CheckInOut: [{ CheckIn: startDate1, CheckOut: endDate1 }, { CheckIn: startDate2, CheckOut: endDate2 }]
    },
    {
        HotelID: 137823,
        HotelName: 'Zanator Hotel',
        Address: "Luisenstr. 56",
        Description: 'A pleasant hotel for polite people. We offer comfort, warmth, and excellent service. Enjoy a relaxing and memorable stay with us.',
        HotelImgID: 'hotel_9',
        Rating: 5,
        ReviewCount: 50,
        Location: { latitude: 40.633829, longitude: -73.967230, TooltipContent: 'Zanator Hotel, New York' },
        HotelFacility: 'Parking, Pet allowed',
        RoomID: 2,
        RoomImgID: 'room_10',
        RoomName: 'Beta Room',
        Capacity: 3,
        ExtraBed: 3,
        ExtraBedCost: 200,
        DiscountPercentage: 7,
        TaxPercentage: 4,
        Extras: 'Pay at visit, Credit card accepted',
        RoomFacility: 'Television, Internet',
        Price: 300,
        CheckInOut: [{ CheckIn: startDate2, CheckOut: endDate2 }]
    },
    {
        HotelID: 137823,
        HotelName: 'Zanator Hotel',
        Address: "Luisenstr. 56",
        Description: 'A pleasant hotel for polite people. We offer comfort, warmth, and excellent service. Enjoy a relaxing and memorable stay with us.',
        HotelImgID: 'hotel_9',
        Rating: 5,
        ReviewCount: 50,
        Location: { latitude: 40.633829, longitude: -73.967230, TooltipContent: 'Zanator Hotel, New York' },
        HotelFacility: 'Parking, Pet allowed',
        RoomID: 3,
        RoomImgID: 'room_11',
        RoomName: 'Gamma Room',
        Capacity: 2,
        ExtraBed: 4,
        ExtraBedCost: 300,
        DiscountPercentage: 8,
        TaxPercentage: 2,
        Extras: 'Free cancellation',
        RoomFacility: 'Television, Internet',
        Price: 300,
        CheckInOut: [{ CheckIn: startDate5, CheckOut: endDate5 }]
    },
    {
        HotelID: 343211,
        HotelName: 'Bentoo Swikator',
        Address: "66,RuRua do Paço",
        Description: 'Want to experience the gentle, shifting waves of the silent ocean? Embrace tranquility and beauty as you explore the serene waters. Let the oceans calmness refresh your soul.',
        HotelImgID: 'hotel_10',
        Rating: 2,
        ReviewCount: 50,
        Location: { latitude: 37.341648, longitude: -121.197788, TooltipContent: 'Bentoo Swikator, California' },
        HotelFacility: 'Parking, Restaurant, Spa',
        RoomID: 1,
        RoomImgID: 'room_12',
        RoomName: 'Alpha Room',
        Capacity: 5,
        ExtraBed: 2,
        ExtraBedCost: 200,
        DiscountPercentage: 12,
        TaxPercentage: 5,
        Extras: 'Free cancellation, Pay at visit',
        RoomFacility: 'Television, Kitchen',
        Price: 400,
        CheckInOut: [{ CheckIn: startDate4, CheckOut: endDate4 }]
    },
    {
        HotelID: 343211,
        HotelName: 'Bentoo Swikator',
        Address: "66,RuRua do Paço",
        Description: 'Want to experience the gentle, shifting waves of the silent ocean? Embrace tranquility and beauty as you explore the serene waters. Let the oceans calmness refresh your soul.',
        HotelImgID: 'hotel_10',
        Rating: 2,
        ReviewCount: 50,
        Location: { latitude: 37.341648, longitude: -121.197788, TooltipContent: 'Bentoo Swikator, California' },
        HotelFacility: 'Parking, Restaurant, Spa',
        RoomID: 2,
        RoomImgID: 'room_13',
        RoomName: 'Beta Room',
        Capacity: 4,
        ExtraBed: 3,
        ExtraBedCost: 200,
        DiscountPercentage: 8,
        TaxPercentage: 5,
        Extras: 'Free cancellation',
        RoomFacility: 'Internet, Shower',
        Price: 500,
        CheckInOut: [{ CheckIn: startDate3, CheckOut: endDate3 }]
    },
    {
        HotelID: 343211,
        HotelName: 'Bentoo Swikator',
        Address: "66,RuRua do Paço",
        Description: 'Want to experience the gentle, shifting waves of the silent ocean? Embrace tranquility and beauty as you explore the serene waters. Let the oceans calmness refresh your soul.',
        HotelImgID: 'hotel_10',
        Rating: 2,
        ReviewCount: 50,
        Location: { latitude: 37.341648, longitude: -121.197788, TooltipContent: 'Bentoo Swikator, California' },
        HotelFacility: 'Parking, Restaurant, Spa',
        RoomID: 3,
        RoomImgID: 'room_14',
        RoomName: 'Gamma Room',
        Capacity: 3,
        ExtraBed: 3,
        ExtraBedCost: 250,
        DiscountPercentage: 8,
        TaxPercentage: 5,
        Extras: 'Free cancellation',
        RoomFacility: 'Internet, Shower',
        Price: 250,
        CheckInOut: [{ CheckIn: startDate2, CheckOut: endDate2 }]
    },
    {
        HotelID: 142278,
        HotelName: 'ZZntor Hotel',
        Address: "333, rue du Commerce",
        Description: 'We are an award-winning hotel, offering exceptional service and luxury. Experience the best in hospitality with us. Your perfect stay starts here.',
        HotelImgID: 'hotel_11',
        Rating: 4,
        ReviewCount: 35,
        Location: { latitude: 45.322690, longitude: -106.781689, TooltipContent: 'ZZntor Hotel, Montana' },
        HotelFacility: 'Parking, Swiming pool',
        RoomID: 1,
        RoomImgID: 'room_15',
        RoomName: 'Alpha Room',
        Capacity: 6,
        ExtraBed: 5,
        ExtraBedCost: 300,
        DiscountPercentage: 10,
        TaxPercentage: 6,
        Extras: 'Free cancellation',
        RoomFacility: 'Television, Whiteboard, Kitchen, Internet, Shower',
        Price: 220,
        CheckInOut: [{ CheckIn: startDate1, CheckOut: endDate1 }]
    },
    {
        HotelID: 142278,
        HotelName: 'ZZntor Hotel',
        Address: "333, rue du Commerce",
        Description: 'We are an award-winning hotel, offering exceptional service and luxury. Experience the best in hospitality with us. Your perfect stay starts here.',
        HotelImgID: 'hotel_11',
        Rating: 4,
        ReviewCount: 35,
        Location: { latitude: 45.322690, longitude: -106.781689, TooltipContent: 'ZZntor Hotel, Montana' },
        HotelFacility: 'Parking, Swiming pool',
        RoomID: 2,
        RoomImgID: 'room_16',
        RoomName: 'Beta Room',
        Capacity: 4,
        ExtraBed: 3,
        ExtraBedCost: 200,
        DiscountPercentage: 5,
        TaxPercentage: 2,
        Extras: 'Pay at visit',
        RoomFacility: 'Whiteboard, Kitchen, Internet',
        Price: 300,
        CheckInOut: [{ CheckIn: startDate1, CheckOut: endDate1 }]
    },
    {
        HotelID: 142278,
        HotelName: 'ZZntor Hotel',
        Address: "333, rue du Commerce",
        Description: 'We are an award-winning hotel, offering exceptional service and luxury. Experience the best in hospitality with us. Your perfect stay starts here.',
        HotelImgID: 'hotel_11',
        Rating: 4,
        ReviewCount: 35,
        Location: { latitude: 45.322690, longitude: -106.781689, TooltipContent: 'ZZntor Hotel, Montana' },
        HotelFacility: 'Parking, Swiming pool',
        RoomID: 3,
        RoomImgID: 'room_1',
        RoomName: 'Gamma Room',
        Capacity: 2,
        ExtraBed: 3,
        ExtraBedCost: 200,
        DiscountPercentage: 8,
        TaxPercentage: 3,
        Extras: 'Free cancellation, Pay at visit',
        RoomFacility: 'Television, Internet',
        Price: 150,
        CheckInOut: [{ CheckIn: startDate4, CheckOut: endDate4 }]
    },
    {
        HotelID: 129823,
        HotelName: 'Oakator Hotel',
        Address: "255, RU Boulevard Tirou",
        Description: 'A pleasant hotel for sweet people. We offer warmth, comfort, and great service. Enjoy a delightful stay with us.',
        HotelImgID: 'hotel_1',
        Rating: 5,
        ReviewCount: 50,
        Location: { latitude: 40.633829, longitude: -73.967230, TooltipContent: 'Oakator Hotel, New York' },
        HotelFacility: 'Swiming pool, Restaurant',
        RoomID: 1,
        RoomImgID: 'room_2',
        RoomName: 'Alpha Room',
        Capacity: 7,
        ExtraBed: 3,
        ExtraBedCost: 200,
        DiscountPercentage: 8,
        TaxPercentage: 2,
        Extras: 'Credit card accepted',
        RoomFacility: 'Projector, Balcony, Kitchen, Internet',
        Price: 300,
        CheckInOut: [{ CheckIn: startDate2, CheckOut: endDate2 }, { CheckIn: startDate3, CheckOut: endDate3 }]
    },
    {
        HotelID: 129823,
        HotelName: 'Oakator Hotel',
        Address: "255, RU Boulevard Tirou",
        Description: 'A pleasant hotel for sweet people. We offer warmth, comfort, and great service. Enjoy a delightful stay with us.',
        HotelImgID: 'hotel_1',
        Rating: 5,
        ReviewCount: 50,
        Location: { latitude: 40.633829, longitude: -73.967230, TooltipContent: 'Oakator Hotel, New York' },
        HotelFacility: 'Swiming pool, Restaurant',
        RoomID: 2,
        RoomImgID: 'room_3',
        RoomName: 'Beta Room',
        Capacity: 3,
        ExtraBed: 3,
        ExtraBedCost: 50,
        DiscountPercentage: 9,
        TaxPercentage: 5,
        Extras: 'Free cancellation, Pay at visit',
        RoomFacility: 'Television, Kitchen, Internet',
        Price: 300,
        CheckInOut: [{ CheckIn: startDate2, CheckOut: endDate2 }]
    },
    {
        HotelID: 129823,
        HotelName: 'Oakator Hotel',
        Address: "255, RU Boulevard Tirou",
        Description: 'A pleasant hotel for sweet people. We offer warmth, comfort, and great service. Enjoy a delightful stay with us.',
        HotelImgID: 'hotel_1',
        Rating: 5,
        ReviewCount: 50,
        Location: { latitude: 40.633829, longitude: -73.967230, TooltipContent: 'Oakator Hotel, New York' },
        HotelFacility: 'Swiming pool, Restaurant',
        RoomID: 3,
        RoomImgID: 'room_4',
        RoomName: 'Gamma Room',
        Capacity: 2,
        ExtraBed: 2,
        ExtraBedCost: 200,
        DiscountPercentage: 9,
        TaxPercentage: 5,
        Extras: 'Free cancellation',
        RoomFacility: 'Television, Internet',
        Price: 100,
        CheckInOut: [{ CheckIn: startDate5, CheckOut: endDate5 }]
    },
    {
        HotelID: 332221,
        HotelName: 'ZenZen Swikator',
        Address: "66, Rua do Paço, GG",
        Description: 'Want to explore a stunning, silent sea in a marvelous hotel? Experience tranquility and luxury with us. Enjoy a peaceful and unforgettable stay.',
        HotelImgID: 'hotel_2',
        Rating: 3,
        ReviewCount: 22,
        Location: { latitude: 37.341648, longitude: -121.197788, TooltipContent: 'ZenZen Swikator, California' },
        HotelFacility: 'Restaurant',
        RoomID: 1,
        RoomImgID: 'room_5',
        RoomName: 'Alpha Room',
        Capacity: 5,
        ExtraBed: 1,
        ExtraBedCost: 200,
        DiscountPercentage: 7,
        TaxPercentage: 3,
        Extras: 'Free cancellation, Credit card accepted, Pay at visit',
        RoomFacility: 'Television, Internet, Shower',
        Price: 330,
        CheckInOut: [{ CheckIn: startDate2, CheckOut: endDate2 }]
    },
    {
        HotelID: 332221,
        HotelName: 'ZenZen Swikator',
        Address: "66, Rua do Paço, GG",
        Description: 'Want to explore a stunning, silent sea in a marvelous hotel? Experience tranquility and luxury with us. Enjoy a peaceful and unforgettable stay.',
        HotelImgID: 'hotel_2',
        Rating: 3,
        ReviewCount: 22,
        Location: { latitude: 37.341648, longitude: -121.197788, TooltipContent: 'ZenZen Swikator, California' },
        HotelFacility: 'Restaurant',
        RoomID: 2,
        RoomImgID: 'room_6',
        RoomName: 'Beta Room',
        Capacity: 4,
        ExtraBed: 3,
        ExtraBedCost: 500,
        DiscountPercentage: 9,
        TaxPercentage: 5,
        Extras: 'Free cancellation',
        RoomFacility: 'Television, Internet, Shower',
        Price: 600,
        CheckInOut: [{ CheckIn: startDate1, CheckOut: endDate1 }, { CheckIn: startDate3, CheckOut: endDate3 }]
    },
    {
        HotelID: 332221,
        HotelName: 'ZenZen Swikator',
        Address: "66, Rua do Paço, GG",
        Description: 'Want to explore a stunning, silent sea in a marvelous hotel? Experience tranquility and luxury with us. Enjoy a peaceful and unforgettable stay.',
        HotelImgID: 'hotel_2',
        Rating: 3,
        ReviewCount: 22,
        Location: { latitude: 37.341648, longitude: -121.197788, TooltipContent: 'ZenZen Swikator, California' },
        HotelFacility: 'Restaurant',
        RoomID: 3,
        RoomImgID: 'room_7',
        RoomName: 'Gamma Room',
        Capacity: 3,
        ExtraBed: 3,
        ExtraBedCost: 200,
        DiscountPercentage: 8,
        TaxPercentage: 5,
        Extras: 'Pay at visit',
        RoomFacility: 'Internet, Shower',
        Price: 150,
        CheckInOut: [{ CheckIn: startDate2, CheckOut: endDate2 }]
    },
    {
        HotelID: 342311,
        HotelName: 'CenCake Owikator',
        Address: "Hauptstr. 31 Mt GG",
        Description: 'Want to explore a marvelous hotel by the marvelous ocean? Experience luxury, tranquility, and breathtaking views. Enjoy an unforgettable stay with us.',
        HotelImgID: 'hotel_3',
        Rating: 3,
        ReviewCount: 30,
        Location: { latitude: 37.341648, longitude: -121.197788, TooltipContent: 'CenCake Owikator, California' },
        HotelFacility: 'Spa',
        RoomID: 1,
        RoomImgID: 'room_8',
        RoomName: 'Alpha Room',
        Capacity: 5,
        ExtraBed: 3,
        ExtraBedCost: 50,
        DiscountPercentage: 8,
        TaxPercentage: 5,
        Extras: 'Free cancellation, Credit card accepted, Pay at visit',
        RoomFacility: 'Television, Kitchen, Internet, Shower',
        Price: 600,
        CheckInOut: [{ CheckIn: startDate4, CheckOut: endDate4 }]
    },
    {
        HotelID: 342311,
        HotelName: 'CenCake Owikator',
        Address: "Hauptstr. 31 Mt GG",
        Description: 'Want to explore a marvelous hotel by the marvelous ocean? Experience luxury, tranquility, and breathtaking views. Enjoy an unforgettable stay with us.',
        HotelImgID: 'hotel_3',
        Rating: 3,
        ReviewCount: 30,
        Location: { latitude: 37.341648, longitude: -121.197788, TooltipContent: 'CenCake Owikator, California' },
        HotelFacility: 'Spa',
        RoomID: 2,
        RoomImgID: 'room_9',
        RoomName: 'Beta Room',
        Capacity: 4,
        ExtraBed: 2,
        ExtraBedCost: 200,
        DiscountPercentage: 9,
        TaxPercentage: 5,
        Extras: 'Free cancellation, Credit card accepted, Pay at visit',
        RoomFacility: 'Television, Internet, Shower',
        Price: 300,
        CheckInOut: [{ CheckIn: startDate1, CheckOut: endDate1 }, { CheckIn: startDate3, CheckOut: endDate3 }]
    },
    {
        HotelID: 342311,
        HotelName: 'CenCake Owikator',
        Address: "Hauptstr. 31 Mt GG",
        Description: 'Want to explore a marvelous hotel by the marvelous ocean? Experience luxury, tranquility, and breathtaking views. Enjoy an unforgettable stay with us.',
        HotelImgID: 'hotel_3',
        Rating: 3,
        ReviewCount: 30,
        Location: { latitude: 37.341648, longitude: -121.197788, TooltipContent: 'CenCake Owikator, California' },
        HotelFacility: 'Spa',
        RoomID: 3,
        RoomImgID: 'room_10',
        RoomName: 'Gamma Room',
        Capacity: 3,
        ExtraBed: 2,
        ExtraBedCost: 200,
        DiscountPercentage: 8,
        TaxPercentage: 2,
        Extras: 'Free cancellation, Credit card accepted, Pay at visit',
        RoomFacility: 'Internet',
        Price: 550,
        CheckInOut: [{ CheckIn: startDate2, CheckOut: endDate2 }]
    },
    {
        HotelID: 192278,
        HotelName: 'Zekaorza Hotel',
        Address: "68 rue de l'Abbaye GG",
        Description: 'We have a variety of themed hotels, each offering a unique experience. Enjoy a stay that matches your style and preferences. Discover comfort with a creative touch.',
        HotelImgID: 'hotel_4',
        Rating: 1,
        ReviewCount: 30,
        Location: { latitude: 45.322690, longitude: -106.781689, TooltipContent: 'Zekaorza Hotel, Montana' },
        HotelFacility: 'Pet allowed, Swiming pool, Restaurant',
        RoomID: 1,
        RoomImgID: 'room_11',
        RoomName: 'Alpha Room',
        Capacity: 3,
        ExtraBed: 2,
        ExtraBedCost: 200,
        DiscountPercentage: 12,
        TaxPercentage: 5,
        Extras: 'Pay at visit',
        RoomFacility: 'Television, Kitchen, Internet, Shower',
        Price: 100,
        CheckInOut: [{ CheckIn: startDate4, CheckOut: endDate4 }]
    },
    {
        HotelID: 192278,
        HotelName: 'Zekaorza Hotel',
        Address: "68 rue de l'Abbaye GG",
        Description: 'We have a variety of themed hotels, each offering a unique experience. Enjoy a stay that matches your style and preferences. Discover comfort with a creative touch.',
        HotelImgID: 'hotel_4',
        Rating: 1,
        ReviewCount: 30,
        Location: { latitude: 45.322690, longitude: -106.781689, TooltipContent: 'Zekaorza Hotel, Montana' },
        HotelFacility: 'Pet allowed, Swiming pool, Restaurant',
        RoomID: 2,
        RoomImgID: 'room_12',
        RoomName: 'Beta Room',
        Capacity: 4,
        ExtraBed: 2,
        ExtraBedCost: 400,
        DiscountPercentage: 9,
        TaxPercentage: 3,
        Extras: 'Credit card accepted, Pay at visit',
        RoomFacility: 'Television, Whiteboard, Kitchen',
        Price: 600,
        CheckInOut: [{ CheckIn: startDate1, CheckOut: endDate1 }]
    },
    {
        HotelID: 192278,
        HotelName: 'Zekaorza Hotel',
        Address: "68 rue de l'Abbaye GG",
        Description: 'We have a variety of themed hotels, each offering a unique experience. Enjoy a stay that matches your style and preferences. Discover comfort with a creative touch.',
        HotelImgID: 'hotel_4',
        Rating: 1,
        ReviewCount: 30,
        Location: { latitude: 45.322690, longitude: -106.781689, TooltipContent: 'Zekaorza Hotel, Montana' },
        HotelFacility: 'Pet allowed, Swiming pool, Restaurant',
        RoomID: 3,
        RoomImgID: 'room_13',
        RoomName: 'Gamma Room',
        Capacity: 2,
        ExtraBed: 2,
        ExtraBedCost: 250,
        DiscountPercentage: 6,
        TaxPercentage: 2,
        Extras: 'Free cancellation, Pay at visit',
        RoomFacility: 'Television, Internet',
        Price: 250,
        CheckInOut: [{ CheckIn: startDate4, CheckOut: endDate4 }]
    },
    {
        HotelID: 197823,
        HotelName: 'Zabatorza Hotel',
        Address: "Luisenstr. 56 GG",
        Description: 'A pleasant hotel for polite people. We offer comfort, warmth, and excellent service. Enjoy a relaxing and memorable stay with us.',
        HotelImgID: 'hotel_5',
        Rating: 3,
        ReviewCount: 10,
        Location: { latitude: 40.633829, longitude: -73.967230, TooltipContent: 'Zabatorza Hotel, New York' },
        HotelFacility: 'Parking, Pet allowed',
        RoomID: 1,
        RoomImgID: 'room_14',
        RoomName: 'Alpha Room',
        Capacity: 5,
        ExtraBed: 1,
        ExtraBedCost: 400,
        DiscountPercentage: 10,
        TaxPercentage: 6,
        Extras: 'Free cancellation',
        RoomFacility: 'Television, Projector, Balcony',
        Price: 700,
        CheckInOut: [{ CheckIn: startDate1, CheckOut: endDate1 }, { CheckIn: startDate2, CheckOut: endDate2 }]
    },
    {
        HotelID: 197823,
        HotelName: 'Zabatorza Hotel',
        Address: "Luisenstr. 56 GG",
        Description: 'A pleasant hotel for polite people. We offer comfort, warmth, and excellent service. Enjoy a relaxing and memorable stay with us.',
        HotelImgID: 'hotel_5',
        Rating: 3,
        ReviewCount: 10,
        Location: { latitude: 40.633829, longitude: -73.967230, TooltipContent: 'Zabatorza Hotel, New York' },
        HotelFacility: 'Parking, Pet allowed',
        RoomID: 2,
        RoomImgID: 'room_15',
        RoomName: 'Beta Room',
        Capacity: 3,
        ExtraBed: 3,
        ExtraBedCost: 200,
        DiscountPercentage: 7,
        TaxPercentage: 2,
        Extras: 'Pay at visit, Credit card accepted',
        RoomFacility: 'Television, Internet',
        Price: 500,
        CheckInOut: [{ CheckIn: startDate2, CheckOut: endDate2 }]
    },
    {
        HotelID: 197823,
        HotelName: 'Zabatorza Hotel',
        Address: "Luisenstr. 56 GG",
        Description: 'A pleasant hotel for polite people. We offer comfort, warmth, and excellent service. Enjoy a relaxing and memorable stay with us.',
        HotelImgID: 'hotel_5',
        Rating: 3,
        ReviewCount: 10,
        Location: { latitude: 40.633829, longitude: -73.967230, TooltipContent: 'Zabatorza Hotel, New York' },
        HotelFacility: 'Parking, Pet allowed',
        RoomID: 3,
        RoomImgID: 'room_16',
        RoomName: 'Gamma Room',
        Capacity: 2,
        ExtraBed: 4,
        ExtraBedCost: 300,
        DiscountPercentage: 8,
        TaxPercentage: 2,
        Extras: 'Free cancellation',
        RoomFacility: 'Television',
        Price: 300,
        CheckInOut: [{ CheckIn: startDate4, CheckOut: endDate4 }]
    },
    {
        HotelID: 393211,
        HotelName: 'Saentoo Swikator',
        Address: "66,RuRua do Paço",
        Description: 'Want to experience the gentle, shifting waves of the silent ocean? Embrace tranquility and beauty as you explore the serene waters. Let the oceans calmness refresh your soul.',
        HotelImgID: 'hotel_6',
        Rating: 3,
        ReviewCount: 10,
        Location: { latitude: 37.341648, longitude: -121.197788, TooltipContent: 'Saentoo Swikator, California' },
        HotelFacility: 'Parking, Restaurant, Spa',
        RoomID: 1,
        RoomImgID: 'room_1',
        RoomName: 'Alpha Room',
        Capacity: 5,
        ExtraBed: 2,
        ExtraBedCost: 200,
        DiscountPercentage: 12,
        TaxPercentage: 5,
        Extras: 'Free cancellation, Pay at visit',
        RoomFacility: 'Television, Kitchen',
        Price: 700,
        CheckInOut: [{ CheckIn: startDate2, CheckOut: endDate2 }]
    },
    {
        HotelID: 393211,
        HotelName: 'Saentoo Swikator',
        Address: "66,RuRua do Paço",
        Description: 'Want to experience the gentle, shifting waves of the silent ocean? Embrace tranquility and beauty as you explore the serene waters. Let the oceans calmness refresh your soul.',
        HotelImgID: 'hotel_6',
        Rating: 3,
        ReviewCount: 10,
        Location: { latitude: 37.341648, longitude: -121.197788, TooltipContent: 'Saentoo Swikator, California' },
        HotelFacility: 'Parking, Restaurant, Spa',
        RoomID: 2,
        RoomImgID: 'room_2',
        RoomName: 'Beta Room',
        Capacity: 4,
        ExtraBed: 3,
        ExtraBedCost: 200,
        DiscountPercentage: 8,
        TaxPercentage: 5,
        Extras: 'Free cancellation',
        RoomFacility: 'Internet, Shower',
        Price: 300,
        CheckInOut: [{ CheckIn: startDate2, CheckOut: endDate2 }]
    },
    {
        HotelID: 393211,
        HotelName: 'Saentoo Swikator',
        Address: "66,RuRua do Paço",
        Description: 'Want to experience the gentle, shifting waves of the silent ocean? Embrace tranquility and beauty as you explore the serene waters. Let the oceans calmness refresh your soul.',
        HotelImgID: 'hotel_6',
        Rating: 3,
        ReviewCount: 10,
        Location: { latitude: 37.341648, longitude: -121.197788, TooltipContent: 'Saentoo Swikator, California' },
        HotelFacility: 'Parking, Restaurant, Spa',
        RoomID: 3,
        RoomImgID: 'room_3',
        RoomName: 'Gamma Room',
        Capacity: 3,
        ExtraBed: 3,
        ExtraBedCost: 250,
        DiscountPercentage: 8,
        TaxPercentage: 5,
        Extras: 'Free cancellation',
        RoomFacility: 'Internet, Shower',
        Price: 250,
        CheckInOut: [{ CheckIn: startDate2, CheckOut: endDate2 }, { CheckIn: startDate3, CheckOut: endDate3 }]
    },
    {
        HotelID: 199278,
        HotelName: 'Zoontor Hotel',
        Address: "333, rue du Commerce",
        Description: 'We are an award-winning hotel, offering exceptional service and luxury. Experience the best in hospitality with us. Your perfect stay starts here.',
        HotelImgID: 'hotel_7',
        Rating: 1,
        ReviewCount: 35,
        Location: { latitude: 45.322690, longitude: -106.781689, TooltipContent: 'Zoontor Hotel, Montana' },
        HotelFacility: 'Parking, Swiming pool',
        RoomID: 1,
        RoomImgID: 'room_4',
        RoomName: 'Alpha Room',
        Capacity: 6,
        ExtraBed: 5,
        ExtraBedCost: 300,
        DiscountPercentage: 10,
        TaxPercentage: 6,
        Extras: 'Free cancellation',
        RoomFacility: 'Television, Whiteboard, Kitchen, Internet, Shower',
        Price: 290,
        CheckInOut: [{ CheckIn: startDate3, CheckOut: endDate3 }]
    },
    {
        HotelID: 199278,
        HotelName: 'Zoontor Hotel',
        Address: "333, rue du Commerce",
        Description: 'We are an award-winning hotel, offering exceptional service and luxury. Experience the best in hospitality with us. Your perfect stay starts here.',
        HotelImgID: 'hotel_7',
        Rating: 1,
        ReviewCount: 35,
        Location: { latitude: 45.322690, longitude: -106.781689, TooltipContent: 'Zoontor Hotel, Montana' },
        HotelFacility: 'Parking, Swiming pool',
        RoomID: 2,
        RoomImgID: 'room_5',
        RoomName: 'Beta Room',
        Capacity: 4,
        ExtraBed: 3,
        ExtraBedCost: 200,
        DiscountPercentage: 8,
        TaxPercentage: 3,
        Extras: 'Pay at visit',
        RoomFacility: 'Whiteboard, Kitchen, Internet',
        Price: 100,
        CheckInOut: [{ CheckIn: startDate1, CheckOut: endDate1 }]
    },
    {
        HotelID: 199278,
        HotelName: 'Zoontor Hotel',
        Address: "333, rue du Commerce",
        Description: 'We are an award-winning hotel, offering exceptional service and luxury. Experience the best in hospitality with us. Your perfect stay starts here.',
        HotelImgID: 'hotel_7',
        Rating: 1,
        ReviewCount: 35,
        Location: { latitude: 45.322690, longitude: -106.781689, TooltipContent: 'Zoontor Hotel, Montana' },
        HotelFacility: 'Parking, Swiming pool',
        RoomID: 3,
        RoomImgID: 'room_6',
        RoomName: 'Gamma Room',
        Capacity: 2,
        ExtraBed: 3,
        ExtraBedCost: 200,
        DiscountPercentage: 8,
        TaxPercentage: 3,
        Extras: 'Free cancellation, Pay at visit',
        RoomFacility: 'Television, Internet',
        Price: 150,
        CheckInOut: [{ CheckIn: startDate3, CheckOut: endDate3 }]
    },
    {
        HotelID: 199923,
        HotelName: 'Sasktor Hotel',
        Address: "255, RU Boulevard Tirou GG",
        Description: 'A pleasant hotel for sweet people. We offer warmth, comfort, and great service. Enjoy a delightful stay with us.',
        HotelImgID: 'hotel_8',
        Rating: 2,
        ReviewCount: 50,
        Location: { latitude: 40.633829, longitude: -73.967230, TooltipContent: 'Sasktor Hotel, New York' },
        HotelFacility: 'Swiming pool, Restaurant',
        RoomID: 1,
        RoomImgID: 'room_7',
        RoomName: 'Alpha Room',
        Capacity: 3,
        ExtraBed: 3,
        ExtraBedCost: 200,
        DiscountPercentage: 8,
        TaxPercentage: 2,
        Extras: 'Credit card accepted',
        RoomFacility: 'Projector, Balcony, Kitchen, Internet',
        Price: 290,
        CheckInOut: [{ CheckIn: startDate2, CheckOut: endDate2 }]
    },

];

export const data: Hotel[] = hotelData;

export interface Location {
    latitude: number;
    longitude: number;
    TooltipContent: string;
}

export interface CheckInOut {
    CheckIn: Date;
    CheckOut: Date;
}

export interface Hotel {
    HotelID: number;
    HotelName: string;
    Address: string;
    Description: string;
    HotelImgID: string;
    Rating: number;
    ReviewCount: number;
    Location: Location;
    HotelFacility: string;
    RoomID: number;
    RoomImgID: string;
    RoomName: string;
    Capacity: number;
    ExtraBed: number;
    ExtraBedCost: number;
    DiscountPercentage: number;
    TaxPercentage: number;
    Extras: string;
    RoomFacility: string;
    Price: number;
    CheckInOut: CheckInOut[];
}