Object.defineProperty(exports, "__esModule", { value: true });

const startDate1 = new Date();
const endDate1 = new Date(startDate1);
endDate1.setDate(startDate1.getDate() + 2);

const startDate2 = new Date(endDate1);
startDate2.setDate(endDate1.getDate() + 1);
const endDate2 = new Date(startDate2);
endDate2.setDate(startDate2.getDate() + 2);

var hotelInfo = [
    {
        HotelID: 102278,
        HotelName: 'Benor Cotel',
        Address: "59 rue de l'Abbaye",
        Description: 'We are the king of the hotel.',
        HotelImgID: 'hotel_1',
        Rating: 5,
        ReviewCount: 20,
        Location: { latitude: 45.322690, longitude: -106.781689, TooltipContent: 'Benor Cotel, Montana' },
        HotelFacility: 'Parking, Pet allowed, Swiming pool, Restaurant',
        RoomID: 1,
        RoomImgID: 'room_1',
        RoomName: 'Alpha Room',
        Capacity: 6,
        ExtraBed: 3,
        ExtraBedCost: 200,
        DiscountPercentage: 8,
        TaxPercentage: 5,
        Extras: 'Free cancellation, Credit card accepted, Pay at visit',
        RoomFacility: 'Television, Projector, Balcony, Whiteboard, Kitchen, Internet, Shower',
        Price: 500,
        CheckInOut: []
    },
    {
        HotelID: 102278,
        HotelName: 'Benor Cotel',
        Address: "59 rue de l'Abbaye",
        Description: 'We are the king of the hotel.',
        HotelImgID: 'hotel_1',
        Rating: 5,
        ReviewCount: 20,
        Location: { latitude: 45.322690, longitude: -106.781689, TooltipContent: 'Benor Cotel, Montana' },
        HotelFacility: 'Parking, Pet allowed, Swiming pool, Restaurant',
        RoomID: 2,
        RoomImgID: 'room_2',
        RoomName: 'Beta Room',
        Capacity: 4,
        ExtraBed: 2,
        ExtraBedCost: 300,
        DiscountPercentage: 9,
        TaxPercentage: 6,
        Extras: 'Credit card accepted, Pay at visit',
        RoomFacility: 'Television, Whiteboard, Kitchen, Internet',
        Price: 300,
        CheckInOut: [{ CheckIn: startDate1, CheckOut: endDate1 }]
    },
    {
        HotelID: 102278,
        HotelName: 'Benor Cotel',
        Address: "59 rue de l'Abbaye",
        Description: 'We are the king of the hotel.',
        HotelImgID: 'hotel_1',
        Rating: 5,
        ReviewCount: 20,
        Location: { latitude: 45.322690, longitude: -106.781689, TooltipContent: 'Benor Cotel, Montana' },
        HotelFacility: 'Parking, Pet allowed, Swiming pool, Restaurant',
        RoomID: 3,
        RoomImgID: 'room_3',
        RoomName: 'Gamma Room',
        Capacity: 2,
        ExtraBed: 2,
        ExtraBedCost: 150,
        DiscountPercentage: 6,
        TaxPercentage: 3,
        Extras: 'Free cancellation, Pay at visit',
        RoomFacility: 'Television, Internet',
        Price: 150,
        CheckInOut: []
    },
    ////////////////////////////////
    {
        HotelID: 117823,
        HotelName: 'Zabator Cotel',
        Address: "Luisenstr. 48",
        Description: 'Pleasent hotel for pleasent people.',
        HotelImgID: 'hotel_2',
        Rating: 4,
        ReviewCount: 30,
        Location: { latitude: 40.633829, longitude: -73.967230, TooltipContent: 'Zabator Cotel, New York' },
        HotelFacility: 'Parking, Swiming pool, Restaurant',
        RoomID: 1,
        RoomImgID: 'room_4',
        RoomName: 'Alpha Room',
        Capacity: 7,
        ExtraBed: 5,
        ExtraBedCost: 100,
        DiscountPercentage: 10,
        TaxPercentage: 7,
        Extras: 'Free cancellation',
        RoomFacility: 'Television, Projector, Balcony, Kitchen, Internet',
        Price: 600,
        CheckInOut: [{ CheckIn: startDate1, CheckOut: endDate1 }, { CheckIn: startDate2, CheckOut: endDate2 }]
    },
    {
        HotelID: 117823,
        HotelName: 'Zabator Cotel',
        Address: "Luisenstr. 48",
        Description: 'Pleasent hotel for pleasent people.',
        HotelImgID: 'hotel_2',
        Rating: 4,
        ReviewCount: 30,
        Location: { latitude: 40.633829, longitude: -73.967230, TooltipContent: 'Zabator Cotel, New York' },
        HotelFacility: 'Parking, Swiming pool, Restaurant',
        RoomID: 2,
        RoomImgID: 'room_5',
        RoomName: 'Beta Room',
        Capacity: 3,
        ExtraBed: 3,
        ExtraBedCost: 200,
        DiscountPercentage: 7,
        TaxPercentage: 4,
        Extras: 'Pay at visit',
        RoomFacility: 'Television, Kitchen, Internet',
        Price: 300,
        CheckInOut: [{ CheckIn: startDate2, CheckOut: endDate2 }]
    },
    {
        HotelID: 117823,
        HotelName: 'Zabator Cotel',
        Address: "Luisenstr. 48",
        Description: 'Pleasent hotel for pleasent people.',
        HotelImgID: 'hotel_2',
        Rating: 4,
        ReviewCount: 30,
        Location: { latitude: 40.633829, longitude: -73.967230, TooltipContent: 'Zabator Cotel, New York' },
        HotelFacility: 'Parking, Swiming pool, Restaurant',
        RoomID: 3,
        RoomImgID: 'room_6',
        RoomName: 'Gamma Room',
        Capacity: 2,
        ExtraBed: 3,
        ExtraBedCost: 300,
        DiscountPercentage: 5,
        TaxPercentage: 2,
        Extras: 'Free cancellation',
        RoomFacility: 'Television, Internet',
        Price: 100,
        CheckInOut: []
    },
    ////////////////////////////////
    {
        HotelID: 322211,
        HotelName: 'Ben Swikator',
        Address: "Rua do Paço, 67",
        Description: 'Want to explore wave silent see in marvelous hotel.',
        HotelImgID: 'hotel_3',
        Rating: 3,
        ReviewCount: 18,
        Location: { latitude: 37.341648, longitude: -121.197788, TooltipContent: 'Ben Swikator, California' },
        HotelFacility: 'Parking, Restaurant, Spa',
        RoomID: 1,
        RoomImgID: 'room_7',
        RoomName: 'Alpha Room',
        Capacity: 5,
        ExtraBed: 1,
        ExtraBedCost: 500,
        DiscountPercentage: 12,
        TaxPercentage: 9,
        Extras: 'Free cancellation, Credit card accepted, Pay at visit',
        RoomFacility: 'Television, Kitchen, Internet, Shower',
        Price: 600,
        CheckInOut: []
    },
    {
        HotelID: 322211,
        HotelName: 'Ben Swikator',
        Address: "Rua do Paço, 67",
        Description: 'Want to explore wave silent see in marvelous hotel.',
        HotelImgID: 'hotel_3',
        Rating: 3,
        ReviewCount: 18,
        Location: { latitude: 37.341648, longitude: -121.197788, TooltipContent: 'Ben Swikator, California' },
        HotelFacility: 'Parking, Restaurant, Spa',
        RoomID: 2,
        RoomImgID: 'room_8',
        RoomName: 'Beta Room',
        Capacity: 4,
        ExtraBed: 3,
        ExtraBedCost: 100,
        DiscountPercentage: 8,
        TaxPercentage: 5,
        Extras: 'Free cancellation',
        RoomFacility: 'Television, Internet, Shower',
        Price: 300,
        CheckInOut: [{ CheckIn: startDate1, CheckOut: endDate1 }]
    },
    {
        HotelID: 322211,
        HotelName: 'Ben Swikator',
        Address: "Rua do Paço, 67",
        Description: 'Want to explore wave silent see in marvelous hotel.',
        HotelImgID: 'hotel_3',
        Rating: 3,
        ReviewCount: 18,
        Location: { latitude: 37.341648, longitude: -121.197788, TooltipContent: 'Ben Swikator, California' },
        HotelFacility: 'Parking, Restaurant, Spa',
        RoomID: 3,
        RoomImgID: 'room_9',
        RoomName: 'Gamma Room',
        Capacity: 3,
        ExtraBed: 3,
        ExtraBedCost: 250,
        DiscountPercentage: 8,
        TaxPercentage: 5,
        Extras: 'Free cancellation',
        RoomFacility: 'Internet, Shower',
        Price: 150,
        CheckInOut: [{ CheckIn: startDate2, CheckOut: endDate2 }]
    },
    //////////////////////////////////////////

    {
        HotelID: 112278,
        HotelName: 'Zentor Motel',
        Address: "2, rue du Commerce",
        Description: 'We are the queen of the hotel.',
        HotelImgID: 'hotel_4',
        Rating: 4,
        ReviewCount: 35,
        Location: { latitude: 45.322690, longitude: -106.781689, TooltipContent: 'Zentor Motel, Montana' },
        HotelFacility: 'Parking, Pet allowed, Swiming pool',
        RoomID: 1,
        RoomImgID: 'room_10',
        RoomName: 'Alpha Room',
        Capacity: 6,
        ExtraBed: 5,
        ExtraBedCost: 300,
        DiscountPercentage: 10,
        TaxPercentage: 7,
        Extras: 'Free cancellation',
        RoomFacility: 'Television, Projector, Balcony, Whiteboard, Kitchen, Internet, Shower',
        Price: 500,
        CheckInOut: []
    },
    {
        HotelID: 112278,
        HotelName: 'Zentor Motel',
        Address: "2, rue du Commerce",
        Description: 'We are the queen of the hotel.',
        HotelImgID: 'hotel_4',
        Rating: 4,
        ReviewCount: 35,
        Location: { latitude: 45.322690, longitude: -106.781689, TooltipContent: 'Zentor Motel, Montana' },
        HotelFacility: 'Parking, Pet allowed, Swiming pool',
        RoomID: 2,
        RoomImgID: 'room_11',
        RoomName: 'Beta Room',
        Capacity: 4,
        ExtraBed: 3,
        ExtraBedCost: 200,
        DiscountPercentage: 5,
        TaxPercentage: 2,
        Extras: 'Free cancellation, Credit card accepted, Pay at visit',
        RoomFacility: 'Television, Whiteboard, Kitchen, Internet',
        Price: 300,
        CheckInOut: [{ CheckIn: startDate1, CheckOut: endDate1 }]
    },
    {
        HotelID: 112278,
        HotelName: 'Zentor Motel',
        Address: "2, rue du Commerce",
        Description: 'We are the queen of the hotel.',
        HotelImgID: 'hotel_4',
        Rating: 4,
        ReviewCount: 35,
        Location: { latitude: 45.322690, longitude: -106.781689, TooltipContent: 'Zentor Motel, Montana' },
        HotelFacility: 'Parking, Pet allowed, Swiming pool',
        RoomID: 3,
        RoomImgID: 'room_12',
        RoomName: 'Gamma Room',
        Capacity: 2,
        ExtraBed: 3,
        ExtraBedCost: 200,
        DiscountPercentage: 8,
        TaxPercentage: 3,
        Extras: 'Free cancellation, Pay at visit',
        RoomFacility: 'Television, Internet',
        Price: 150,
        CheckInOut: []
    },
    ////////////////////////////////
    {
        HotelID: 127823,
        HotelName: 'Bakator Cotel',
        Address: "Boulevard Tirou, 255",
        Description: 'Pleasent hotel for sweet people.',
        HotelImgID: 'hotel_5',
        Rating: 2,
        ReviewCount: 15,
        Location: { latitude: 40.633829, longitude: -73.967230, TooltipContent: 'Bakator Cotel, New York' },
        HotelFacility: 'Swiming pool, Restaurant',
        RoomID: 1,
        RoomImgID: 'room_13',
        RoomName: 'Alpha Room',
        Capacity: 7,
        ExtraBed: 3,
        ExtraBedCost: 200,
        DiscountPercentage: 8,
        TaxPercentage: 2,
        Extras: 'Free cancellation, Credit card accepted, Pay at visit',
        RoomFacility: 'Television, Projector, Balcony, Kitchen, Internet',
        Price: 600,
        CheckInOut: [{ CheckIn: startDate1, CheckOut: endDate1 }, { CheckIn: startDate2, CheckOut: endDate2 }]
    },
    {
        HotelID: 127823,
        HotelName: 'Bakator Cotel',
        Address: "Boulevard Tirou, 255",
        Description: 'Pleasent hotel for sweet people.',
        HotelImgID: 'hotel_5',
        Rating: 2,
        ReviewCount: 15,
        Location: { latitude: 40.633829, longitude: -73.967230, TooltipContent: 'Bakator Cotel, New York' },
        HotelFacility: 'Swiming pool, Restaurant',
        RoomID: 2,
        RoomImgID: 'room_14',
        RoomName: 'Beta Room',
        Capacity: 3,
        ExtraBed: 3,
        ExtraBedCost: 50,
        DiscountPercentage: 9,
        TaxPercentage: 5,
        Extras: 'Free cancellation, Pay at visit',
        RoomFacility: 'Television, Kitchen, Internet',
        Price: 300,
        CheckInOut: [{ CheckIn: startDate2, CheckOut: endDate2 }]
    },
    {
        HotelID: 127823,
        HotelName: 'Bakator Cotel',
        Address: "Boulevard Tirou, 255",
        Description: 'Pleasent hotel for sweet people.',
        HotelImgID: 'hotel_5',
        Rating: 2,
        ReviewCount: 15,
        Location: { latitude: 40.633829, longitude: -73.967230, TooltipContent: 'Bakator Cotel, New York' },
        HotelFacility: 'Swiming pool, Restaurant',
        RoomID: 3,
        RoomImgID: 'room_15',
        RoomName: 'Gamma Room',
        Capacity: 2,
        ExtraBed: 2,
        ExtraBedCost: 200,
        DiscountPercentage: 9,
        TaxPercentage: 5,
        Extras: 'Free cancellation',
        RoomFacility: 'Television, Internet',
        Price: 100,
        CheckInOut: []
    },
    ////////////////////////////////
    {
        HotelID: 332211,
        HotelName: 'Zen Swikator',
        Address: "Rua do Paço, GG",
        Description: 'Want to explore stunning silent see in a marvelous hotel.',
        HotelImgID: 'hotel_6',
        Rating: 5,
        ReviewCount: 22,
        Location: { latitude: 37.341648, longitude: -121.197788, TooltipContent: 'Zen Swikator, California' },
        HotelFacility: 'Restaurant',
        RoomID: 1,
        RoomImgID: 'room_16',
        RoomName: 'Alpha Room',
        Capacity: 5,
        ExtraBed: 1,
        ExtraBedCost: 100,
        DiscountPercentage: 7,
        TaxPercentage: 3,
        Extras: 'Free cancellation, Credit card accepted, Pay at visit',
        RoomFacility: 'Television, Kitchen, Internet, Shower',
        Price: 600,
        CheckInOut: []
    },
    {
        HotelID: 332211,
        HotelName: 'Zen Swikator',
        Address: "Rua do Paço, GG",
        Description: 'Want to explore stunning silent see in a marvelous hotel.',
        HotelImgID: 'hotel_6',
        Rating: 5,
        ReviewCount: 22,
        Location: { latitude: 37.341648, longitude: -121.197788, TooltipContent: 'Zen Swikator, California' },
        HotelFacility: 'Restaurant',
        RoomID: 2,
        RoomImgID: 'room_1',
        RoomName: 'Beta Room',
        Capacity: 4,
        ExtraBed: 3,
        ExtraBedCost: 500,
        DiscountPercentage: 9,
        TaxPercentage: 5,
        Extras: 'Free cancellation',
        RoomFacility: 'Television, Internet, Shower',
        Price: 300,
        CheckInOut: [{ CheckIn: startDate1, CheckOut: endDate1 }]
    },
    {
        HotelID: 332211,
        HotelName: 'Zen Swikator',
        Address: "Rua do Paço, GG",
        Description: 'Want to explore stunning silent see in a marvelous hotel.',
        HotelImgID: 'hotel_6',
        Rating: 5,
        ReviewCount: 22,
        Location: { latitude: 37.341648, longitude: -121.197788, TooltipContent: 'Zen Swikator, California' },
        HotelFacility: 'Restaurant',
        RoomID: 3,
        RoomImgID: 'room_2',
        RoomName: 'Gamma Room',
        Capacity: 3,
        ExtraBed: 3,
        ExtraBedCost: 200,
        DiscountPercentage: 8,
        TaxPercentage: 5,
        Extras: 'Pay at visit',
        RoomFacility: 'Internet, Shower',
        Price: 150,
        CheckInOut: [{ CheckIn: startDate2, CheckOut: endDate2 }]
    },
    /////////////////////////

    {
        HotelID: 342211,
        HotelName: 'Cen Zwikator',
        Address: "Hauptstr. 31",
        Description: 'Want to explore a marvelous hotel.',
        HotelImgID: 'hotel_7',
        Rating: 5,
        ReviewCount: 25,
        Location: { latitude: 37.341648, longitude: -121.197788, TooltipContent: 'Cen Zwikator, California' },
        HotelFacility: 'Spa',
        RoomID: 1,
        RoomImgID: 'room_3',
        RoomName: 'Alpha Room',
        Capacity: 5,
        ExtraBed: 3,
        ExtraBedCost: 50,
        DiscountPercentage: 8,
        TaxPercentage: 5,
        Extras: 'Free cancellation, Credit card accepted, Pay at visit',
        RoomFacility: 'Television, Kitchen, Internet, Shower',
        Price: 600,
        CheckInOut: []
    },
    {
        HotelID: 342211,
        HotelName: 'Cen Zwikator',
        Address: "Hauptstr. 31",
        Description: 'Want to explore a marvelous hotel.',
        HotelImgID: 'hotel_7',
        Rating: 5,
        ReviewCount: 25,
        Location: { latitude: 37.341648, longitude: -121.197788, TooltipContent: 'Cen Zwikator, California' },
        HotelFacility: 'Spa',
        RoomID: 2,
        RoomImgID: 'room_4',
        RoomName: 'Beta Room',
        Capacity: 4,
        ExtraBed: 2,
        ExtraBedCost: 200,
        DiscountPercentage: 9,
        TaxPercentage: 5,
        Extras: 'Free cancellation, Credit card accepted, Pay at visit',
        RoomFacility: 'Television, Internet, Shower',
        Price: 300,
        CheckInOut: [{ CheckIn: startDate1, CheckOut: endDate1 }]
    },
    {
        HotelID: 342211,
        HotelName: 'Cen Zwikator',
        Address: "Hauptstr. 31",
        Description: 'Want to explore a marvelous hotel.',
        HotelImgID: 'hotel_7',
        Rating: 5,
        ReviewCount: 25,
        Location: { latitude: 37.341648, longitude: -121.197788, TooltipContent: 'Cen Zwikator, California' },
        HotelFacility: 'Spa',
        RoomID: 3,
        RoomImgID: 'room_5',
        RoomName: 'Gamma Room',
        Capacity: 3,
        ExtraBed: 2,
        ExtraBedCost: 200,
        DiscountPercentage: 8,
        TaxPercentage: 3,
        Extras: 'Free cancellation, Credit card accepted, Pay at visit',
        RoomFacility: 'Internet, Shower',
        Price: 150,
        CheckInOut: [{ CheckIn: startDate2, CheckOut: endDate2 }]
    },
    //////////////////

    {
        HotelID: 132278,
        HotelName: 'Bekaor Cotel',
        Address: "68 rue de l'Abbaye",
        Description: 'We have different theme hotel.',
        HotelImgID: 'hotel_8',
        Rating: 3,
        ReviewCount: 30,
        Location: { latitude: 45.322690, longitude: -106.781689, TooltipContent: 'Bekaor Cotel, Montana' },
        HotelFacility: 'Pet allowed, Swiming pool, Restaurant',
        RoomID: 1,
        RoomImgID: 'room_6',
        RoomName: 'Alpha Room',
        Capacity: 3,
        ExtraBed: 2,
        ExtraBedCost: 200,
        DiscountPercentage: 12,
        TaxPercentage: 5,
        Extras: 'Pay at visit',
        RoomFacility: 'Television, Kitchen, Internet, Shower',
        Price: 600,
        CheckInOut: []
    },
    {
        HotelID: 132278,
        HotelName: 'Bekaor Cotel',
        Address: "68 rue de l'Abbaye",
        Description: 'We have different theme hotel.',
        HotelImgID: 'hotel_8',
        Rating: 3,
        ReviewCount: 30,
        Location: { latitude: 45.322690, longitude: -106.781689, TooltipContent: 'Bekaor Cotel, Montana' },
        HotelFacility: 'Pet allowed, Swiming pool, Restaurant',
        RoomID: 2,
        RoomImgID: 'room_7',
        RoomName: 'Beta Room',
        Capacity: 4,
        ExtraBed: 2,
        ExtraBedCost: 400,
        DiscountPercentage: 9,
        TaxPercentage: 3,
        Extras: 'Credit card accepted, Pay at visit',
        RoomFacility: 'Television, Whiteboard, Kitchen',
        Price: 200,
        CheckInOut: [{ CheckIn: startDate1, CheckOut: endDate1 }]
    },
    {
        HotelID: 132278,
        HotelName: 'Bekaor Cotel',
        Address: "68 rue de l'Abbaye",
        Description: 'We have different theme hotel.',
        HotelImgID: 'hotel_8',
        Rating: 3,
        ReviewCount: 30,
        Location: { latitude: 45.322690, longitude: -106.781689, TooltipContent: 'Bekaor Cotel, Montana' },
        HotelFacility: 'Pet allowed, Swiming pool, Restaurant',
        RoomID: 3,
        RoomImgID: 'room_8',
        RoomName: 'Gamma Room',
        Capacity: 2,
        ExtraBed: 2,
        ExtraBedCost: 250,
        DiscountPercentage: 6,
        TaxPercentage: 3,
        Extras: 'Free cancellation, Pay at visit',
        RoomFacility: 'Television, Internet',
        Price: 150,
        CheckInOut: []
    },
    ////////////////////////////////
    {
        HotelID: 137823,
        HotelName: 'Zanator Cotel',
        Address: "Luisenstr. 56",
        Description: 'Pleasent hotel for polite people.',
        HotelImgID: 'hotel_9',
        Rating: 5,
        ReviewCount: 50,
        Location: { latitude: 40.633829, longitude: -73.967230, TooltipContent: 'Zanator Cotel, New York' },
        HotelFacility: 'Parking, Pet allowed',
        RoomID: 1,
        RoomImgID: 'room_9',
        RoomName: 'Alpha Room',
        Capacity: 5,
        ExtraBed: 1,
        ExtraBedCost: 400,
        DiscountPercentage: 10,
        TaxPercentage: 6,
        Extras: 'Free cancellation',
        RoomFacility: 'Television, Projector, Balcony',
        Price: 600,
        CheckInOut: [{ CheckIn: startDate1, CheckOut: endDate1 }, { CheckIn: startDate2, CheckOut: endDate2 }]
    },
    {
        HotelID: 137823,
        HotelName: 'Zanator Cotel',
        Address: "Luisenstr. 56",
        Description: 'Pleasent hotel for polite people.',
        HotelImgID: 'hotel_9',
        Rating: 5,
        ReviewCount: 50,
        Location: { latitude: 40.633829, longitude: -73.967230, TooltipContent: 'Zanator Cotel, New York' },
        HotelFacility: 'Parking, Pet allowed',
        RoomID: 2,
        RoomImgID: 'room_10',
        RoomName: 'Beta Room',
        Capacity: 3,
        ExtraBed: 3,
        ExtraBedCost: 200,
        DiscountPercentage: 7,
        TaxPercentage: 4,
        Extras: 'Pay at visit, Credit card accepted',
        RoomFacility: 'Television, Internet',
        Price: 300,
        CheckInOut: [{ CheckIn: startDate2, CheckOut: endDate2 }]
    },
    {
        HotelID: 137823,
        HotelName: 'Zanator Cotel',
        Address: "Luisenstr. 56",
        Description: 'Pleasent hotel for polite people.',
        HotelImgID: 'hotel_9',
        Rating: 5,
        ReviewCount: 50,
        Location: { latitude: 40.633829, longitude: -73.967230, TooltipContent: 'Zanator Cotel, New York' },
        HotelFacility: 'Parking, Pet allowed',
        RoomID: 3,
        RoomImgID: 'room_11',
        RoomName: 'Gamma Room',
        Capacity: 2,
        ExtraBed: 4,
        ExtraBedCost: 300,
        DiscountPercentage: 8,
        TaxPercentage: 2,
        Extras: 'Free cancellation',
        RoomFacility: 'Television, Internet',
        Price: 300,
        CheckInOut: []
    },
    ////////////////////////////////
    {
        HotelID: 343211,
        HotelName: 'Bentoo Swikator',
        Address: "66,RuRua do Paço",
        Description: 'Want to explore shift silent water wave in ocean.',
        HotelImgID: 'hotel_10',
        Rating: 2,
        ReviewCount: 50,
        Location: { latitude: 37.341648, longitude: -121.197788, TooltipContent: 'Bentoo Swikator, California' },
        HotelFacility: 'Parking, Restaurant, Spa',
        RoomID: 1,
        RoomImgID: 'room_12',
        RoomName: 'Alpha Room',
        Capacity: 5,
        ExtraBed: 2,
        ExtraBedCost: 200,
        DiscountPercentage: 12,
        TaxPercentage: 5,
        Extras: 'Free cancellation, Pay at visit',
        RoomFacility: 'Television, Kitchen',
        Price: 400,
        CheckInOut: []
    },
    {
        HotelID: 343211,
        HotelName: 'Bentoo Swikator',
        Address: "66,RuRua do Paço",
        Description: 'Want to explore shift silent water wave in ocean.',
        HotelImgID: 'hotel_10',
        Rating: 2,
        ReviewCount: 50,
        Location: { latitude: 37.341648, longitude: -121.197788, TooltipContent: 'Bentoo Swikator, California' },
        HotelFacility: 'Parking, Restaurant, Spa',
        RoomID: 2,
        RoomImgID: 'room_13',
        RoomName: 'Beta Room',
        Capacity: 4,
        ExtraBed: 3,
        ExtraBedCost: 200,
        DiscountPercentage: 8,
        TaxPercentage: 5,
        Extras: 'Free cancellation',
        RoomFacility: 'Internet, Shower',
        Price: 500,
        CheckInOut: []
    },
    {
        HotelID: 343211,
        HotelName: 'Bentoo Swikator',
        Address: "66,RuRua do Paço",
        Description: 'Want to explore shift silent water wave in ocean.',
        HotelImgID: 'hotel_10',
        Rating: 2,
        ReviewCount: 50,
        Location: { latitude: 37.341648, longitude: -121.197788, TooltipContent: 'Bentoo Swikator, California' },
        HotelFacility: 'Parking, Restaurant, Spa',
        RoomID: 3,
        RoomImgID: 'room_14',
        RoomName: 'Gamma Room',
        Capacity: 3,
        ExtraBed: 3,
        ExtraBedCost: 250,
        DiscountPercentage: 8,
        TaxPercentage: 5,
        Extras: 'Free cancellation',
        RoomFacility: 'Internet, Shower',
        Price: 250,
        CheckInOut: [{ CheckIn: startDate2, CheckOut: endDate2 }]
    },
    //////////////////////////////////////////

    {
        HotelID: 142278,
        HotelName: 'ZZntor Cotel',
        Address: "333, rue du Commerce",
        Description: 'We are the winner hotel.',
        HotelImgID: 'hotel_11',
        Rating: 4,
        ReviewCount: 35,
        Location: { latitude: 45.322690, longitude: -106.781689, TooltipContent: 'ZZntor Cotel, Montana' },
        HotelFacility: 'Parking, Swiming pool',
        RoomID: 1,
        RoomImgID: 'room_15',
        RoomName: 'Alpha Room',
        Capacity: 6,
        ExtraBed: 5,
        ExtraBedCost: 300,
        DiscountPercentage: 10,
        TaxPercentage: 6,
        Extras: 'Free cancellation',
        RoomFacility: 'Television, Whiteboard, Kitchen, Internet, Shower',
        Price: 220,
        CheckInOut: [{ CheckIn: startDate1, CheckOut: endDate1 }]
    },
    {
        HotelID: 142278,
        HotelName: 'ZZntor Cotel',
        Address: "333, rue du Commerce",
        Description: 'We are the winner hotel.',
        HotelImgID: 'hotel_11',
        Rating: 4,
        ReviewCount: 35,
        Location: { latitude: 45.322690, longitude: -106.781689, TooltipContent: 'ZZntor Cotel, Montana' },
        HotelFacility: 'Parking, Swiming pool',
        RoomID: 2,
        RoomImgID: 'room_16',
        RoomName: 'Beta Room',
        Capacity: 4,
        ExtraBed: 3,
        ExtraBedCost: 200,
        DiscountPercentage: 5,
        TaxPercentage: 2,
        Extras: 'Pay at visit',
        RoomFacility: 'Whiteboard, Kitchen, Internet',
        Price: 300,
        CheckInOut: [{ CheckIn: startDate1, CheckOut: endDate1 }]
    },
    {
        HotelID: 142278,
        HotelName: 'ZZntor Cotel',
        Address: "333, rue du Commerce",
        Description: 'We are the winner hotel.',
        HotelImgID: 'hotel_11',
        Rating: 4,
        ReviewCount: 35,
        Location: { latitude: 45.322690, longitude: -106.781689, TooltipContent: 'ZZntor Cotel, Montana' },
        HotelFacility: 'Parking, Swiming pool',
        RoomID: 3,
        RoomImgID: 'room_1',
        RoomName: 'Gamma Room',
        Capacity: 2,
        ExtraBed: 3,
        ExtraBedCost: 200,
        DiscountPercentage: 8,
        TaxPercentage: 3,
        Extras: 'Free cancellation, Pay at visit',
        RoomFacility: 'Television, Internet',
        Price: 150,
        CheckInOut: []
    },
    ////////////////////////////////
    {
        HotelID: 129823,
        HotelName: 'Oakator Cotel',
        Address: "255, RU Boulevard Tirou",
        Description: 'Pleasent hotel for sweet people.',
        HotelImgID: 'hotel_1',
        Rating: 5,
        ReviewCount: 50,
        Location: { latitude: 40.633829, longitude: -73.967230, TooltipContent: 'Oakator Cotel, New York' },
        HotelFacility: 'Swiming pool, Restaurant',
        RoomID: 1,
        RoomImgID: 'room_2',
        RoomName: 'Alpha Room',
        Capacity: 7,
        ExtraBed: 3,
        ExtraBedCost: 200,
        DiscountPercentage: 8,
        TaxPercentage: 2,
        Extras: 'Credit card accepted',
        RoomFacility: 'Projector, Balcony, Kitchen, Internet',
        Price: 300,
        CheckInOut: [{ CheckIn: startDate2, CheckOut: endDate2 }]
    },
    {
        HotelID: 129823,
        HotelName: 'Oakator Cotel',
        Address: "255, RU Boulevard Tirou",
        Description: 'Pleasent hotel for sweet people.',
        HotelImgID: 'hotel_1',
        Rating: 5,
        ReviewCount: 50,
        Location: { latitude: 40.633829, longitude: -73.967230, TooltipContent: 'Oakator Cotel, New York' },
        HotelFacility: 'Swiming pool, Restaurant',
        RoomID: 2,
        RoomImgID: 'room_3',
        RoomName: 'Beta Room',
        Capacity: 3,
        ExtraBed: 3,
        ExtraBedCost: 50,
        DiscountPercentage: 9,
        TaxPercentage: 5,
        Extras: 'Free cancellation, Pay at visit',
        RoomFacility: 'Television, Kitchen, Internet',
        Price: 300,
        CheckInOut: [{ CheckIn: startDate2, CheckOut: endDate2 }]
    },
    {
        HotelID: 129823,
        HotelName: 'Oakator Cotel',
        Address: "255, RU Boulevard Tirou",
        Description: 'Pleasent hotel for sweet people.',
        HotelImgID: 'hotel_1',
        Rating: 5,
        ReviewCount: 50,
        Location: { latitude: 40.633829, longitude: -73.967230, TooltipContent: 'Oakator Cotel, New York' },
        HotelFacility: 'Swiming pool, Restaurant',
        RoomID: 3,
        RoomImgID: 'room_4',
        RoomName: 'Gamma Room',
        Capacity: 2,
        ExtraBed: 2,
        ExtraBedCost: 200,
        DiscountPercentage: 9,
        TaxPercentage: 5,
        Extras: 'Free cancellation',
        RoomFacility: 'Television, Internet',
        Price: 100,
        CheckInOut: []
    },
    ////////////////////////////////
    {
        HotelID: 332221,
        HotelName: 'ZenZen Swikator',
        Address: "66, Rua do Paço, GG",
        Description: 'Want to explore stunning silent see in a marvelous hotel.',
        HotelImgID: 'hotel_2',
        Rating: 3,
        ReviewCount: 22,
        Location: { latitude: 37.341648, longitude: -121.197788, TooltipContent: 'ZenZen Swikator, California' },
        HotelFacility: 'Restaurant',
        RoomID: 1,
        RoomImgID: 'room_5',
        RoomName: 'Alpha Room',
        Capacity: 5,
        ExtraBed: 1,
        ExtraBedCost: 200,
        DiscountPercentage: 7,
        TaxPercentage: 3,
        Extras: 'Free cancellation, Credit card accepted, Pay at visit',
        RoomFacility: 'Television, Internet, Shower',
        Price: 330,
        CheckInOut: [{ CheckIn: startDate2, CheckOut: endDate2 }]
    },
    {
        HotelID: 332221,
        HotelName: 'ZenZen Swikator',
        Address: "66, Rua do Paço, GG",
        Description: 'Want to explore stunning silent see in a marvelous hotel.',
        HotelImgID: 'hotel_2',
        Rating: 3,
        ReviewCount: 22,
        Location: { latitude: 37.341648, longitude: -121.197788, TooltipContent: 'ZenZen Swikator, California' },
        HotelFacility: 'Restaurant',
        RoomID: 2,
        RoomImgID: 'room_6',
        RoomName: 'Beta Room',
        Capacity: 4,
        ExtraBed: 3,
        ExtraBedCost: 500,
        DiscountPercentage: 9,
        TaxPercentage: 5,
        Extras: 'Free cancellation',
        RoomFacility: 'Television, Internet, Shower',
        Price: 600,
        CheckInOut: [{ CheckIn: startDate1, CheckOut: endDate1 }]
    },
    {
        HotelID: 332221,
        HotelName: 'ZenZen Swikator',
        Address: "66, Rua do Paço, GG",
        Description: 'Want to explore stunning silent see in a marvelous hotel.',
        HotelImgID: 'hotel_2',
        Rating: 3,
        ReviewCount: 22,
        Location: { latitude: 37.341648, longitude: -121.197788, TooltipContent: 'ZenZen Swikator, California' },
        HotelFacility: 'Restaurant',
        RoomID: 3,
        RoomImgID: 'room_7',
        RoomName: 'Gamma Room',
        Capacity: 3,
        ExtraBed: 3,
        ExtraBedCost: 200,
        DiscountPercentage: 8,
        TaxPercentage: 5,
        Extras: 'Pay at visit',
        RoomFacility: 'Internet, Shower',
        Price: 150,
        CheckInOut: [{ CheckIn: startDate2, CheckOut: endDate2 }]
    },
    /////////////////////////

    {
        HotelID: 342311,
        HotelName: 'CenCake Owikator',
        Address: "Hauptstr. 31 Mt GG",
        Description: 'Want to explore a marvelous hotel in marvelous Ocean.',
        HotelImgID: 'hotel_3',
        Rating: 3,
        ReviewCount: 30,
        Location: { latitude: 37.341648, longitude: -121.197788, TooltipContent: 'CenCake Owikator, California' },
        HotelFacility: 'Spa',
        RoomID: 1,
        RoomImgID: 'room_8',
        RoomName: 'Alpha Room',
        Capacity: 5,
        ExtraBed: 3,
        ExtraBedCost: 50,
        DiscountPercentage: 8,
        TaxPercentage: 5,
        Extras: 'Free cancellation, Credit card accepted, Pay at visit',
        RoomFacility: 'Television, Kitchen, Internet, Shower',
        Price: 600,
        CheckInOut: []
    },
    {
        HotelID: 342311,
        HotelName: 'CenCake Owikator',
        Address: "Hauptstr. 31 Mt GG",
        Description: 'Want to explore a marvelous hotel in marvelous Ocean.',
        HotelImgID: 'hotel_3',
        Rating: 3,
        ReviewCount: 30,
        Location: { latitude: 37.341648, longitude: -121.197788, TooltipContent: 'CenCake Owikator, California' },
        HotelFacility: 'Spa',
        RoomID: 2,
        RoomImgID: 'room_9',
        RoomName: 'Beta Room',
        Capacity: 4,
        ExtraBed: 2,
        ExtraBedCost: 200,
        DiscountPercentage: 9,
        TaxPercentage: 5,
        Extras: 'Free cancellation, Credit card accepted, Pay at visit',
        RoomFacility: 'Television, Internet, Shower',
        Price: 300,
        CheckInOut: [{ CheckIn: startDate1, CheckOut: endDate1 }]
    },
    {
        HotelID: 342311,
        HotelName: 'CenCake Owikator',
        Address: "Hauptstr. 31 Mt GG",
        Description: 'Want to explore a marvelous hotel in marvelous Ocean.',
        HotelImgID: 'hotel_3',
        Rating: 3,
        ReviewCount: 30,
        Location: { latitude: 37.341648, longitude: -121.197788, TooltipContent: 'CenCake Owikator, California' },
        HotelFacility: 'Spa',
        RoomID: 3,
        RoomImgID: 'room_10',
        RoomName: 'Gamma Room',
        Capacity: 3,
        ExtraBed: 2,
        ExtraBedCost: 200,
        DiscountPercentage: 8,
        TaxPercentage: 2,
        Extras: 'Free cancellation, Credit card accepted, Pay at visit',
        RoomFacility: 'Internet',
        Price: 550,
        CheckInOut: [{ CheckIn: startDate2, CheckOut: endDate2 }]
    },

    ///////////////////

    {
        HotelID: 192278,
        HotelName: 'Zekaorza Cotel',
        Address: "68 rue de l'Abbaye GG",
        Description: 'We have different theme hotel.',
        HotelImgID: 'hotel_4',
        Rating: 1,
        ReviewCount: 30,
        Location: { latitude: 45.322690, longitude: -106.781689, TooltipContent: 'Zekaorza Cotel, Montana' },
        HotelFacility: 'Pet allowed, Swiming pool, Restaurant',
        RoomID: 1,
        RoomImgID: 'room_11',
        RoomName: 'Alpha Room',
        Capacity: 3,
        ExtraBed: 2,
        ExtraBedCost: 200,
        DiscountPercentage: 12,
        TaxPercentage: 5,
        Extras: 'Pay at visit',
        RoomFacility: 'Television, Kitchen, Internet, Shower',
        Price: 100,
        CheckInOut: []
    },
    {
        HotelID: 192278,
        HotelName: 'Zekaorza Cotel',
        Address: "68 rue de l'Abbaye GG",
        Description: 'We have different theme hotel.',
        HotelImgID: 'hotel_4',
        Rating: 1,
        ReviewCount: 30,
        Location: { latitude: 45.322690, longitude: -106.781689, TooltipContent: 'Zekaorza Cotel, Montana' },
        HotelFacility: 'Pet allowed, Swiming pool, Restaurant',
        RoomID: 2,
        RoomImgID: 'room_12',
        RoomName: 'Beta Room',
        Capacity: 4,
        ExtraBed: 2,
        ExtraBedCost: 400,
        DiscountPercentage: 9,
        TaxPercentage: 3,
        Extras: 'Credit card accepted, Pay at visit',
        RoomFacility: 'Television, Whiteboard, Kitchen',
        Price: 600,
        CheckInOut: [{ CheckIn: startDate1, CheckOut: endDate1 }]
    },
    {
        HotelID: 192278,
        HotelName: 'Zekaorza Cotel',
        Address: "68 rue de l'Abbaye GG",
        Description: 'We have different theme hotel.',
        HotelImgID: 'hotel_4',
        Rating: 1,
        ReviewCount: 30,
        Location: { latitude: 45.322690, longitude: -106.781689, TooltipContent: 'Zekaorza Cotel, Montana' },
        HotelFacility: 'Pet allowed, Swiming pool, Restaurant',
        RoomID: 3,
        RoomImgID: 'room_13',
        RoomName: 'Gamma Room',
        Capacity: 2,
        ExtraBed: 2,
        ExtraBedCost: 250,
        DiscountPercentage: 6,
        TaxPercentage: 2,
        Extras: 'Free cancellation, Pay at visit',
        RoomFacility: 'Television, Internet',
        Price: 250,
        CheckInOut: []
    },
    ////////////////////////////////
    {
        HotelID: 197823,
        HotelName: 'Zabatorza Cotel',
        Address: "Luisenstr. 56 GG",
        Description: 'Pleasent hotel for polite people.',
        HotelImgID: 'hotel_5',
        Rating: 3,
        ReviewCount: 10,
        Location: { latitude: 40.633829, longitude: -73.967230, TooltipContent: 'Zabatorza Cotel, New York' },
        HotelFacility: 'Parking, Pet allowed',
        RoomID: 1,
        RoomImgID: 'room_14',
        RoomName: 'Alpha Room',
        Capacity: 5,
        ExtraBed: 1,
        ExtraBedCost: 400,
        DiscountPercentage: 10,
        TaxPercentage: 6,
        Extras: 'Free cancellation',
        RoomFacility: 'Television, Projector, Balcony',
        Price: 700,
        CheckInOut: [{ CheckIn: startDate1, CheckOut: endDate1 }, { CheckIn: startDate2, CheckOut: endDate2 }]
    },
    {
        HotelID: 197823,
        HotelName: 'Zabatorza Cotel',
        Address: "Luisenstr. 56 GG",
        Description: 'Pleasent hotel for polite people.',
        HotelImgID: 'hotel_5',
        Rating: 3,
        ReviewCount: 10,
        Location: { latitude: 40.633829, longitude: -73.967230, TooltipContent: 'Zabatorza Cotel, New York' },
        HotelFacility: 'Parking, Pet allowed',
        RoomID: 2,
        RoomImgID: 'room_15',
        RoomName: 'Beta Room',
        Capacity: 3,
        ExtraBed: 3,
        ExtraBedCost: 200,
        DiscountPercentage: 7,
        TaxPercentage: 2,
        Extras: 'Pay at visit, Credit card accepted',
        RoomFacility: 'Television, Internet',
        Price: 500,
        CheckInOut: [{ CheckIn: startDate2, CheckOut: endDate2 }]
    },
    {
        HotelID: 197823,
        HotelName: 'Zabatorza Cotel',
        Address: "Luisenstr. 56 GG",
        Description: 'Pleasent hotel for polite people.',
        HotelImgID: 'hotel_5',
        Rating: 3,
        ReviewCount: 10,
        Location: { latitude: 40.633829, longitude: -73.967230, TooltipContent: 'Zabatorza Cotel, New York' },
        HotelFacility: 'Parking, Pet allowed',
        RoomID: 3,
        RoomImgID: 'room_16',
        RoomName: 'Gamma Room',
        Capacity: 2,
        ExtraBed: 4,
        ExtraBedCost: 300,
        DiscountPercentage: 8,
        TaxPercentage: 2,
        Extras: 'Free cancellation',
        RoomFacility: 'Television',
        Price: 300,
        CheckInOut: []
    },
    ////////////////////////////////
    {
        HotelID: 393211,
        HotelName: 'Saentoo Swikator',
        Address: "66,RuRua do Paço",
        Description: 'Want to explore shift silent water wave in ocean.',
        HotelImgID: 'hotel_6',
        Rating: 3,
        ReviewCount: 10,
        Location: { latitude: 37.341648, longitude: -121.197788, TooltipContent: 'Saentoo Swikator, California' },
        HotelFacility: 'Parking, Restaurant, Spa',
        RoomID: 1,
        RoomImgID: 'room_1',
        RoomName: 'Alpha Room',
        Capacity: 5,
        ExtraBed: 2,
        ExtraBedCost: 200,
        DiscountPercentage: 12,
        TaxPercentage: 5,
        Extras: 'Free cancellation, Pay at visit',
        RoomFacility: 'Television, Kitchen',
        Price: 700,
        CheckInOut: [{ CheckIn: startDate2, CheckOut: endDate2 }]
    },
    {
        HotelID: 393211,
        HotelName: 'Saentoo Swikator',
        Address: "66,RuRua do Paço",
        Description: 'Want to explore shift silent water wave in ocean.',
        HotelImgID: 'hotel_6',
        Rating: 3,
        ReviewCount: 10,
        Location: { latitude: 37.341648, longitude: -121.197788, TooltipContent: 'Saentoo Swikator, California' },
        HotelFacility: 'Parking, Restaurant, Spa',
        RoomID: 2,
        RoomImgID: 'room_2',
        RoomName: 'Beta Room',
        Capacity: 4,
        ExtraBed: 3,
        ExtraBedCost: 200,
        DiscountPercentage: 8,
        TaxPercentage: 5,
        Extras: 'Free cancellation',
        RoomFacility: 'Internet, Shower',
        Price: 300,
        CheckInOut: [{ CheckIn: startDate2, CheckOut: endDate2 }]
    },
    {
        HotelID: 393211,
        HotelName: 'Saentoo Swikator',
        Address: "66,RuRua do Paço",
        Description: 'Want to explore shift silent water wave in ocean.',
        HotelImgID: 'hotel_6',
        Rating: 3,
        ReviewCount: 10,
        Location: { latitude: 37.341648, longitude: -121.197788, TooltipContent: 'Saentoo Swikator, California' },
        HotelFacility: 'Parking, Restaurant, Spa',
        RoomID: 3,
        RoomImgID: 'room_3',
        RoomName: 'Gamma Room',
        Capacity: 3,
        ExtraBed: 3,
        ExtraBedCost: 250,
        DiscountPercentage: 8,
        TaxPercentage: 5,
        Extras: 'Free cancellation',
        RoomFacility: 'Internet, Shower',
        Price: 250,
        CheckInOut: [{ CheckIn: startDate2, CheckOut: endDate2 }]
    },
    //////////////////////////////////////////

    {
        HotelID: 199278,
        HotelName: 'Zoontor Cotel',
        Address: "333, rue du Commerce",
        Description: 'We are the winner hotel.',
        HotelImgID: 'hotel_7',
        Rating: 1,
        ReviewCount: 35,
        Location: { latitude: 45.322690, longitude: -106.781689, TooltipContent: 'Zoontor Cotel, Montana' },
        HotelFacility: 'Parking, Swiming pool',
        RoomID: 1,
        RoomImgID: 'room_4',
        RoomName: 'Alpha Room',
        Capacity: 6,
        ExtraBed: 5,
        ExtraBedCost: 300,
        DiscountPercentage: 10,
        TaxPercentage: 6,
        Extras: 'Free cancellation',
        RoomFacility: 'Television, Whiteboard, Kitchen, Internet, Shower',
        Price: 290,
        CheckInOut: []
    },
    {
        HotelID: 199278,
        HotelName: 'Zoontor Cotel',
        Address: "333, rue du Commerce",
        Description: 'We are the winner hotel.',
        HotelImgID: 'hotel_7',
        Rating: 1,
        ReviewCount: 35,
        Location: { latitude: 45.322690, longitude: -106.781689, TooltipContent: 'Zoontor Cotel, Montana' },
        HotelFacility: 'Parking, Swiming pool',
        RoomID: 2,
        RoomImgID: 'room_5',
        RoomName: 'Beta Room',
        Capacity: 4,
        ExtraBed: 3,
        ExtraBedCost: 200,
        DiscountPercentage: 8,
        TaxPercentage: 3,
        Extras: 'Pay at visit',
        RoomFacility: 'Whiteboard, Kitchen, Internet',
        Price: 100,
        CheckInOut: [{ CheckIn: startDate1, CheckOut: endDate1 }]
    },
    {
        HotelID: 199278,
        HotelName: 'Zoontor Cotel',
        Address: "333, rue du Commerce",
        Description: 'We are the winner hotel.',
        HotelImgID: 'hotel_7',
        Rating: 1,
        ReviewCount: 35,
        Location: { latitude: 45.322690, longitude: -106.781689, TooltipContent: 'Zoontor Cotel, Montana' },
        HotelFacility: 'Parking, Swiming pool',
        RoomID: 3,
        RoomImgID: 'room_6',
        RoomName: 'Gamma Room',
        Capacity: 2,
        ExtraBed: 3,
        ExtraBedCost: 200,
        DiscountPercentage: 8,
        TaxPercentage: 3,
        Extras: 'Free cancellation, Pay at visit',
        RoomFacility: 'Television, Internet',
        Price: 150,
        CheckInOut: []
    },
    ////////////////////////////////
    {
        HotelID: 199923,
        HotelName: 'Sasktor Cotel',
        Address: "255, RU Boulevard Tirou GG",
        Description: 'Pleasent hotel for sweet people.',
        HotelImgID: 'hotel_8',
        Rating: 2,
        ReviewCount: 50,
        Location: { latitude: 40.633829, longitude: -73.967230, TooltipContent: 'Sasktor Cotel, New York' },
        HotelFacility: 'Swiming pool, Restaurant',
        RoomID: 1,
        RoomImgID: 'room_7',
        RoomName: 'Alpha Room',
        Capacity: 3,
        ExtraBed: 3,
        ExtraBedCost: 200,
        DiscountPercentage: 8,
        TaxPercentage: 2,
        Extras: 'Credit card accepted',
        RoomFacility: 'Projector, Balcony, Kitchen, Internet',
        Price: 290,
        CheckInOut: [{ CheckIn: startDate2, CheckOut: endDate2 }]
    },

];

exports.hotelData = hotelInfo;